### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by DarkSlice1** [LavaGang/MelonLoader#102]
based on 0.4.3 with only the bhaptics mod I get the following at startup

guessing the new version of VRchat is to blame here

```
[20:39:07.821] [ERROR] 
[20:39:07.832] [ERROR] Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
[20:39:07.833] [ERROR]    at UnhollowerRuntimeLib.XrefScans.XrefScannerLowLevel.ExtractTargetAddress(Instruction& instruction)
[20:39:07.834] [ERROR]    at UnhollowerRuntimeLib.XrefScans.XrefScannerLowLevel.<JumpTargetsImpl>d__1.MoveNext()
[20:39:07.834] [ERROR]    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
[20:39:07.835] [ERROR]    at UnhollowerRuntimeLib.XrefScans.XrefScanMetadataGenerationUtil.FindMetadataInitForMethod(MethodRewriteContext method, Int64 gameAssemblyBase)
[20:39:07.836] [ERROR]    at AssemblyUnhollower.Passes.Pass16ScanMethodRefs.<>c__DisplayClass2_0.<DoPass>b__2(MethodRewriteContext originalTypeMethod)
[20:39:07.837] [ERROR]    at System.Linq.Parallel.ForAllOperator`1.ForAllEnumerator`1.MoveNext(TInput& currentElement, Int32& currentKey)
[20:39:07.838] [ERROR]    at System.Linq.Parallel.ForAllSpoolingTask`2.SpoolingWork()
[20:39:07.838] [ERROR]    at System.Linq.Parallel.SpoolingTaskBase.Work()
[20:39:07.839] [ERROR]    at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
[20:39:07.840] [ERROR]    at System.Threading.Tasks.Task.Execute()
[20:39:07.841] [ERROR]    --- End of inner exception stack trace ---
[20:39:07.841] [ERROR]    at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
[20:39:07.842] [ERROR]    at System.Linq.Parallel.DefaultMergeHelper`2.System.Linq.Parallel.IMergeHelper<TInputOutput>.Execute()
[20:39:07.843] [ERROR]    at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
[20:39:07.844] [ERROR]    at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
[20:39:07.844] [ERROR]    at System.Linq.Parallel.ForAllOperator`1.WrapPartitionedStream[TKey](PartitionedStream`2 inputStream, IPartitionedStreamRecipient`1 recipient, Boolean preferStriping, QuerySettings settings)
[20:39:07.845] [ERROR]    at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.ChildResultsRecipient.Receive[TKey](PartitionedStream`2 inputStream)
[20:39:07.846] [ERROR]    at System.Linq.Parallel.ScanQueryOperator`1.ScanEnumerableQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
[20:39:07.849] [ERROR]    at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
[20:39:07.850] [ERROR]    at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
[20:39:07.851] [ERROR]    at System.Linq.Parallel.ForAllOperator`1.RunSynchronously()
[20:39:07.852] [ERROR]    at AssemblyUnhollower.Passes.Pass16ScanMethodRefs.DoPass(RewriteGlobalContext context, UnhollowerOptions options)
[20:39:07.853] [ERROR]    at AssemblyUnhollower.Program.Main(UnhollowerOptions options)
[20:39:07.853] [ERROR]    at AssemblyUnhollower.Program.Main(String[] args)
[20:39:08.370] Done in 00:00:01.4225833

```
[Latest.log](https://github.com/LavaGang/MelonLoader/files/6984888/Latest.log)
@HerpDerpinstine  FYI :)

**Comment by DarkSlice1** [comment]
got it working - re-validated files and reinstalled melonLoader :D yay
