### ISSUE TITLE
[Enhancement]: Support for Unity version 2021.3.1f1

### ISSUE THREAD

**Issue by kecleon** [LavaGang/MelonLoader#257]
### Describe the new feature or enhancement

MelonLoader fails to initialize on games using new Unity versions, mods do not work as well when they are installed. Is there planned support for new Unity versions?

Here are startup logs for RotMG after MelonLoader is installed:
```
[15:19:45.221] ------------------------------
[15:19:45.221] MelonLoader v0.5.4 Open-Beta
[15:19:45.221] OS: Windows 10
[15:19:45.222] Hash Code: 99102531024810154100579910097100505048995753975597975597101485351514856
[15:19:45.222] ------------------------------
[15:19:45.223] Game Type: Il2Cpp
[15:19:45.223] Game Arch: x64
[15:19:45.223] ------------------------------
[15:19:45.224] Core::BasePath = C:\Users\Evan\Documents\RealmOfTheMadGod\Production
[15:19:45.224] Game::BasePath = C:\Users\Evan\Documents\RealmOfTheMadGod\Production
[15:19:45.224] Game::DataPath = C:\Users\Evan\Documents\RealmOfTheMadGod\Production\RotMG Exalt_Data
[15:19:45.225] Game::ApplicationPath = C:\Users\Evan\Documents\RealmOfTheMadGod\Production\RotMG Exalt.exe

[15:19:48.523] [ERROR] Failed to Initialize Assets Manager!
[15:19:48.525] ------------------------------
[15:19:48.526] Game Name: UNKNOWN
[15:19:48.526] Game Developer: UNKNOWN
[15:19:48.527] Unity Version: 2021.3.1f1
[15:19:48.527] Game Version: 0
[15:19:48.527] ------------------------------
[15:19:48.976] Preferences Loaded!
[15:19:49.028] [Il2CppUnityTls] Patching mono_unity_get_unitytls_interface...
[15:19:49.028] [Il2CppUnityTls] Patching il2cpp_unity_install_unitytls_interface...
[15:19:49.302] [Il2CppUnityTls] Calling Il2CppInstallUnityTlsInterface...
[15:19:49.304] Loading Plugins...

[15:19:49.307] ------------------------------
[15:19:49.308] No Plugins Loaded!
[15:19:49.308] ------------------------------

[15:19:49.812] Loading Il2CppAssemblyGenerator...
[15:19:49.881] Contacting RemoteAPI...
[15:19:50.651] RemoteAPI.DumperVersion = null
[15:19:50.652] RemoteAPI.UnhollowerVersion = null
[15:19:50.653] RemoteAPI.ObfuscationRegex = null
[15:19:50.653] RemoteAPI.MappingURL = null
[15:19:50.654] RemoteAPI.MappingFileSHA512 = null
[15:19:50.656] Using Dumper Version: 2022.1.0-pre-release.3
[15:19:50.657] Using Il2CppAssemblyUnhollower Version = 0.4.18.0
[15:19:50.658] Using Unity Dependencies Version = 2021.3.1
[15:19:50.658] Using Deobfuscation Regex = null
[15:19:50.659] Downloading Cpp2IL...
[15:19:50.659] Downloading https://github.com/SamboyCoding/Cpp2IL/releases/download/2022.1.0-pre-release.3/Cpp2IL-2022.1.0-pre-release.3-Windows-Netframework472.zip to C:\Users\Evan\Documents\RealmOfTheMadGod\Production\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL_2022.1.0-pre-release.3.zip
[15:19:53.001] Processing Cpp2IL...
[15:19:53.022] Creating Directory C:\Users\Evan\Documents\RealmOfTheMadGod\Production\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL
[15:19:53.022] Extracting C:\Users\Evan\Documents\RealmOfTheMadGod\Production\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL_2022.1.0-pre-release.3.zip to C:\Users\Evan\Documents\RealmOfTheMadGod\Production\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL
[15:19:53.850] Downloading Il2CppAssemblyUnhollower...
[15:19:53.850] Downloading https://github.com/knah/Il2CppAssemblyUnhollower/releases/download/v0.4.18.0/Il2CppAssemblyUnhollower.0.4.18.0.zip to C:\Users\Evan\Documents\RealmOfTheMadGod\Production\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Il2CppAssemblyUnhollower_0.4.18.0.zip
[15:19:54.752] Processing Il2CppAssemblyUnhollower...
[15:19:54.753] Creating Directory C:\Users\Evan\Documents\RealmOfTheMadGod\Production\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Il2CppAssemblyUnhollower
[15:19:54.753] Extracting C:\Users\Evan\Documents\RealmOfTheMadGod\Production\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Il2CppAssemblyUnhollower_0.4.18.0.zip to C:\Users\Evan\Documents\RealmOfTheMadGod\Production\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Il2CppAssemblyUnhollower
[15:19:55.106] Downloading UnityDependencies...
[15:19:55.106] Downloading https://github.com/LavaGang/Unity-Runtime-Libraries/raw/master/2021.3.1.zip to C:\Users\Evan\Documents\RealmOfTheMadGod\Production\MelonLoader\Dependencies\Il2CppAssemblyGenerator\UnityDependencies_2021.3.1.zip
[15:19:57.517] Processing UnityDependencies...
[15:19:57.517] Creating Directory C:\Users\Evan\Documents\RealmOfTheMadGod\Production\MelonLoader\Dependencies\Il2CppAssemblyGenerator\UnityDependencies
[15:19:57.518] Extracting C:\Users\Evan\Documents\RealmOfTheMadGod\Production\MelonLoader\Dependencies\Il2CppAssemblyGenerator\UnityDependencies_2021.3.1.zip to C:\Users\Evan\Documents\RealmOfTheMadGod\Production\MelonLoader\Dependencies\Il2CppAssemblyGenerator\UnityDependencies
[15:19:58.803] Checking GameAssembly...
[15:19:59.319] Assembly Generation Needed!
[15:19:59.323] Executing Cpp2IL...
[15:19:59.325] "C:\Users\Evan\Documents\RealmOfTheMadGod\Production\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL\Cpp2IL.exe" --game-path "C:\Users\Evan\Documents\RealmOfTheMadGod\Production" --exe-name "RotMG Exalt" --use-processor attributeinjector --output-as dummydll
[15:19:59.483] ===Cpp2IL by Samboy063===
[15:19:59.484] A Tool to Reverse Unity's "il2cpp" Build Process.
[15:19:59.484] Version 2022.1.0-pre-release.3
[15:19:59.484]
[15:19:59.485] [Warn] [Program] NO_COLOR set, disabling ANSI color codes as you requested.
[15:19:59.486] [Info] [Program] Running on Win32NT
[15:19:59.594] [Info] [Plugins] Using Plugin: Cpp2IL Built-In
[15:19:59.607] [Info] [Program] Determined game's unity version to be 2021.2.6
[15:19:59.678] [Info] [Library] Initializing Metadata...
[15:19:59.679] [Info] [Library]         Using actual IL2CPP Metadata version 29
[15:20:00.298] [Info] [Library] Initialized Metadata in 621ms
[15:20:00.299] [Info] [Library] Using binary type Portable Executable (from LibCpp2IL)
[15:20:00.300] [Info] [Library] Searching Binary for Required Data...
[15:20:04.300] [Info] [Library] Got Binary codereg: 0x18314D840, metareg: 0x1834689D0 in 4000ms.
[15:20:04.301] [Info] [Library] Initializing Binary...
[15:20:04.472] [Info] [Library] Initialized Binary in 172ms
[15:20:04.589] [Info] [Library] Mapping pointers to Il2CppMethodDefinitions...Processed 185056 OK (118ms)
[15:20:05.123] [Info] [Program] Creating application model...Done.
[15:20:05.123] [Info] [Program] Running processor Attribute Injector...
[15:20:05.574] [Info] [Program] Processor Attribute Injector finished in 450.5604ms
[15:20:05.575] [Info] [Program] Outputting as Stub ("Dummy") DLL Files to C:\Users\Evan\Documents\RealmOfTheMadGod\Production\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL\cpp2il_out...
[15:20:07.189] [ERROR]
[15:20:07.250] [ERROR] Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.ArgumentException: Type is not a primitive
[15:20:07.250] [ERROR] Parameter name: type
[15:20:07.251] [ERROR]    at Cpp2IL.Core.Utils.AsmResolverUtils.GetPrimitiveTypeDef(Il2CppTypeEnum type) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Utils\AsmResolverUtils.cs:line 45
[15:20:07.251] [ERROR]    at Cpp2IL.Core.Utils.AsmResolverAssemblyPopulator.GetTypeSigFromAttributeArg(AssemblyDefinition parentAssembly, BaseCustomAttributeParameter parameter) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Utils\AsmResolverAssemblyPopulator.cs:line 84
[15:20:07.252] [ERROR]    at Cpp2IL.Core.Utils.AsmResolverAssemblyPopulator.FromAnalyzedAttributeProperty(AssemblyDefinition parentAssembly, CustomAttributeProperty property) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Utils\AsmResolverAssemblyPopulator.cs:line 119
[15:20:07.252] [ERROR]    at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
[15:20:07.253] [ERROR]    at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
[15:20:07.257] [ERROR]    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
[15:20:07.258] [ERROR]    at AsmResolver.DotNet.Signatures.CustomAttributeSignature..ctor(IEnumerable`1 fixedArguments, IEnumerable`1 namedArguments)
[15:20:07.259] [ERROR]    at Cpp2IL.Core.Utils.AsmResolverAssemblyPopulator.CopyCustomAttributes(HasCustomAttributes source, IList`1 destination) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Utils\AsmResolverAssemblyPopulator.cs:line 144
[15:20:07.260] [ERROR]    at Cpp2IL.Core.Utils.AsmResolverAssemblyPopulator.PopulateCustomAttributes(AssemblyAnalysisContext asmContext) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Utils\AsmResolverAssemblyPopulator.cs:line 171
[15:20:07.261] [ERROR]    at Cpp2IL.Core.Utils.MiscUtils.<>c__DisplayClass13_0`1.<ExecuteParallel>b__0(T t) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Utils\MiscUtils.cs:line 262
[15:20:07.262] [ERROR]    at System.Linq.Parallel.PartitionedDataSource`1.ListContiguousIndexRangeEnumerator.MoveNext(T& currentElement, Int32& currentKey)
[15:20:07.262] [ERROR]    at System.Linq.Parallel.StopAndGoSpoolingTask`2.SpoolingWork()
[15:20:07.269] [ERROR]    at System.Linq.Parallel.SpoolingTaskBase.Work()
[15:20:07.270] [ERROR]    at System.Linq.Parallel.QueryTask.BaseWork(Object unused)
[15:20:07.276] [ERROR]    at System.Threading.Tasks.Task.Execute()
[15:20:07.277] [ERROR]    --- End of inner exception stack trace ---
[15:20:07.278] [ERROR]    at System.Linq.Parallel.QueryTaskGroupState.QueryEnd(Boolean userInitiatedDispose)
[15:20:07.279] [ERROR]    at System.Linq.Parallel.MergeExecutor`1.Execute[TKey](PartitionedStream`2 partitions, Boolean ignoreOutput, ParallelMergeOptions options, TaskScheduler taskScheduler, Boolean isOrdered, CancellationState cancellationState, Int32 queryId)
[15:20:07.292] [ERROR]    at System.Linq.Parallel.PartitionedStreamMerger`1.Receive[TKey](PartitionedStream`2 partitionedStream)
[15:20:07.296] [ERROR]    at System.Linq.Parallel.UnaryQueryOperator`2.UnaryQueryOperatorResults.GivePartitionedStream(IPartitionedStreamRecipient`1 recipient)
[15:20:07.303] [ERROR]    at System.Linq.Parallel.QueryOperator`1.GetOpenedEnumerator(Nullable`1 mergeOptions, Boolean suppressOrder, Boolean forEffect, QuerySettings querySettings)
[15:20:07.304] [ERROR]    at System.Linq.Parallel.QueryOpeningEnumerator`1.OpenQuery()
[15:20:07.308] [ERROR]    at System.Linq.Parallel.QueryOpeningEnumerator`1.MoveNext()
[15:20:07.310] [ERROR]    at System.Linq.ParallelEnumerable.ToList[TSource](ParallelQuery`1 source)
[15:20:07.311] [ERROR]    at Cpp2IL.Core.CorePlugin.AsmResolverDummyDllOutputFormat.DoOutput(ApplicationAnalysisContext context, String outputRoot) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\CorePlugin\AsmResolverDummyDllOutputFormat.cs:line 48
[15:20:07.312] [ERROR]    at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 340
[15:20:07.322] [ERROR]    at Cpp2IL.Program.Main(String[] args) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 268


[15:20:09.038] Loading Mods...

[15:20:09.040] ------------------------------
[15:20:09.041] No Mods Loaded!
[15:20:09.046] ------------------------------
[15:20:09.084] [ERROR] No Support Module Loaded!
```

Thanks!

**Comment by SlidyDev** [comment]
![Screenshot_20220625-074717_Opera GX.jpg](https://user-images.githubusercontent.com/61495410/175760203-c2271799-f322-4556-97ce-b70f5b599bf8.jpg)
