### ISSUE TITLE
[Bug]: MelonLoader does not work with new popular game "Metal: Hellsinger" 

### ISSUE THREAD

**Issue by yrichard6208** [LavaGang/MelonLoader#297]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

MelonLoader does not work with new popular game "Metal: Hellsinger". This game has a free demo version on Steam.

Here is the error log I saw:
[11:57:21.136] [ERROR] Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.Exception: CustomAttributePrimitiveParameter constructed with a non-primitive type: IL2CPP_TYPE_VALUETYPE
[11:57:21.137] [ERROR]    at Cpp2IL.Core.Model.CustomAttributes.CustomAttributePrimitiveParameter.ReadFromV29Blob(BinaryReader reader, ApplicationAnalysisContext context) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Model\CustomAttributes\CustomAttributePrimitiveParameter.cs:line 92
[11:57:21.138] [ERROR]    at Cpp2IL.Core.Model.CustomAttributes.CustomAttributeArrayParameter.ReadFromV29Blob(BinaryReader reader, ApplicationAnalysisContext context) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Model\CustomAttributes\CustomAttributeArrayParameter.cs:line 71
[11:57:21.139] [ERROR]    at Cpp2IL.Core.Utils.V29AttributeUtils.ReadAttribute(Stream stream, MethodAnalysisContext constructor, ApplicationAnalysisContext context) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Utils\V29AttributeUtils.cs:line 42
[11:57:21.139] [ERROR]    at Cpp2IL.Core.Model.Contexts.HasCustomAttributes.AnalyzeCustomAttributeDataV29() in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Model\Contexts\HasCustomAttributes.cs:line 219
[11:57:21.140] [ERROR]    at Cpp2IL.Core.Model.Contexts.HasCustomAttributes.AnalyzeCustomAttributeData() in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Model\Contexts\HasCustomAttributes.cs:line 199
[11:57:21.141] [ERROR]    at Cpp2IL.Core.CorePlugin.AttributeInjectorProcessingLayer.ProcessCustomAttributesForContext(HasCustomAttributes context, FieldAnalysisContext nameField, FieldAnalysisContext rvaField, FieldAnalysisContext offsetField, MethodAnalysisContext ctor) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\CorePlugin\AttributeInjectorProcessingLayer.cs:line 148
[11:57:21.142] [ERROR]    at Cpp2IL.Core.CorePlugin.AttributeInjectorProcessingLayer.<>c__DisplayClass8_0.<InjectAttributeAttribute>b__1(HasCustomAttributes c) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\CorePlugin\AttributeInjectorProcessingLayer.cs:line 140
[11:57:21.142] [ERROR]    at System.Threading.Tasks.Parallel.<>c__DisplayClass42_0`2.<PartitionerForEachWorker>b__1()
[11:57:21.142] [ERROR]    at System.Threading.Tasks.Task.InnerInvokeWithArg(Task childTask)
[11:57:21.143] [ERROR]    at System.Threading.Tasks.Task.<>c__DisplayClass176_0.<ExecuteSelfReplicating>b__0(Object <p0>)
[11:57:21.144] [ERROR]    --- End of inner exception stack trace ---
[11:57:21.148] [ERROR]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[11:57:21.148] [ERROR]    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
[11:57:21.149] [ERROR]    at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
[11:57:21.150] [ERROR]    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
[11:57:21.150] [ERROR]    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, Action`1 body)
[11:57:21.151] [ERROR]    at Cpp2IL.Core.CorePlugin.AttributeInjectorProcessingLayer.InjectAttributeAttribute(ApplicationAnalysisContext appContext) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\CorePlugin\AttributeInjectorProcessingLayer.cs:line 125
[11:57:21.152] [ERROR]    at Cpp2IL.Core.CorePlugin.AttributeInjectorProcessingLayer.Process(ApplicationAnalysisContext appContext, Action`2 progressCallback) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\CorePlugin\AttributeInjectorProcessingLayer.cs:line 19
[11:57:21.152] [ERROR]    at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 331
[11:57:21.153] [ERROR]    at Cpp2IL.Program.Main(String[] args) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 268

[MelonLoader_22-09-21_11-57-05.191.log](https://github.com/LavaGang/MelonLoader/files/9618372/MelonLoader_22-09-21_11-57-05.191.log)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by slxdy** [comment]
@SamboyCoding

**Comment by SamboyCoding** [comment]
Should be fixed in 0.5.5 with the updated cpp2il, no?

**Comment by yrichard6208** [comment]
Could you provide instructions on how to manually update cpp2il, I can test it to see if it works.

**Comment by nitrog0d** [comment]
Use this build of MelonLoader since it wasn't updated to 0.5.5 yet
https://github.com/LavaGang/MelonLoader/suites/8354438293/artifacts/368090029

**Comment by yrichard6208** [comment]
@nitrog0d Thanks a lot, this build does solve the problem and work with the game!
