### ISSUE TITLE
When I try to start Bonelab Melon loader starts up and then halfway through it starting up when it gets to this mod called force developer it shuts down and I cant play it anymore, if someone could help me that would be amazing.[Bug]: 

### ISSUE THREAD

**Issue by Stalebread-107** [LavaGang/MelonLoader#441]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

When I try to start Bonelab Melon loader starts up and then halfway through it starting up when it gets to this mod called force developer it shuts down and I cant play it anymore, if someone could help me that would be amazing.[Bug]: 

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [x] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
does MelonLoader work without mods? if so, this isn't our issue and you have to talk to the mod developer. Please post a log.

**Comment by RedLgend** [comment]
It works without mods but as soon as i get 1 mod, it freezes and crashes. it on bloonsTD6. this error comes in the console:
Caught exception invoking Start! System.IO.FileNotFoundException: Could not load file or assembly 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'Assembly-CSharp, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   at System.Reflection.CustomAttribute.CreateCaObject(RuntimeModule module, RuntimeType type, IRuntimeMethodInfo ctor, IntPtr& blob, IntPtr blobEnd, Int32& namedArgs)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeModule decoratedModule, Int32 decoratedMetadataToken, Int32 pcaCount, RuntimeType attributeFilterType)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeAssembly assembly, RuntimeType caType)
   at System.Reflection.RuntimeAssembly.GetCustomAttributes(Type attributeType, Boolean inherit)
   at System.Attribute.GetCustomAttributes(Assembly element, Boolean inherit)
   at MelonLoader.MelonUtils.PullAttributesFromAssembly[T](Assembly asm, Boolean inherit) in D:\a\MelonLoader\MelonLoader\MelonLoader\MelonUtils.cs:line 216
   at MelonLoader.MelonAssembly.LoadMelons() in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\MelonAssembly.cs:line 228
   at MelonLoader.MelonHandler.LoadMelonsFromDirectory[T](String path) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\MelonHandler.cs:line 62
   at MelonLoader.Core.Start() in D:\a\MelonLoader\MelonLoader\MelonLoader\Core.cs:line 112
   at MelonLoader.NativeHost.NativeEntryPoint.Start() in D:\a\MelonLoader\MelonLoader\MelonLoader.NativeHost\NativeEntryPoint.cs:line 75

pls help

**Comment by Nepozilian** [comment]
I am also having this problem

**Comment by Nepozilian** [comment]
And all I can say is PLEASE HELP

**Comment by Skaticus** [comment]
diwngrade MelonLoader to 0.57 with rhe MelonLoader.Installer.exe  
ir should work then.
![Screenshot 2023-07-28 230539](https://github.com/LavaGang/MelonLoader/assets/87941485/928df852-5081-4461-a8f4-4d0b4e9b2018)

**Comment by rakosi2** [comment]
Correct, Bonelab mods are currently made for ML 0.5.7 and trying to load a 0.5.7 mod into ML 0.6.x will cause a crash. Closing this ticket.

**Comment by WAVESTXR** [comment]
i have the same issue and i tried everything including above still not working can anyone help?

**Comment by KRANKENHAUS2112** [comment]
Yeah, 0.6.4 will actually load into the game for me. I can load mods, but they won't actually show up in game. With mods, I can't even get the game to run on 0.5.7.

**Comment by rakosi2** [comment]
If the game starts without mods but can't with mods then that sounds like a mod issue and there isn't much we can help with that. Also patch5 mods uses ML 0.6.4
