### ISSUE TITLE
[Bug]: this.. uhh.. thing

### ISSUE THREAD

**Issue by NickArcadeNerd** [LavaGang/MelonLoader#499]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [ ] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

System.UnauthorizedAccessException: Access to the path 'C:\Program Files (x86)\Steam\steamapps\common\Fall Guys\dobby.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at MelonLoader.OperationHandler.Automated_Install(String destination, String selected_version, Boolean is_x86, Boolean legacy_version)

### Did you attach your log file?

- [ ] Yes, I attached my log file to the text box above.
- [X] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by NickArcadeNerd** [comment]
sorry to waste ur time

**Comment by RinLovesYou** [comment]
>Fall guys, unsupported, stop trying to mod that game.

**Comment by NickArcadeNerd** [comment]
ok
