### ISSUE TITLE
[Bug]: System.UnauthorizedAccessException

### ISSUE THREAD

**Issue by Acidic8401** [LavaGang/MelonLoader#509]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Full ``Latest.log`` file included. If no file exists then leave this unchecked and state so.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

System.UnauthorizedAccessException: Access to the path 'C:\Program Files\RotMG Exalt Launcher\dobby.dll' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at MelonLoader.OperationHandler.Automated_Install(String destination, String selected_version, Boolean is_x86, Boolean legacy_version)

### Did you attach your log file?

- [X] Yes, I attached my log file to the text box above.
- [ ] No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by RinLovesYou** [comment]
Simply a permission issue. Make sure your have access to all files in the game folder. Not really a melonloader issue
