### ISSUE TITLE
[Bug]: Error on Start House Party after game update "Failed to Download UnityDependencies!"

### ISSUE THREAD

**Issue by trilias** [LavaGang/MelonLoader#592]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Failed to Download UnityDependencies!

[21:00:25.402] [Il2CppAssemblyGenerator] Downloading UnityDependencies...
[21:00:25.403] [Il2CppAssemblyGenerator] Downloading https://github.com/LavaGang/Unity-Runtime-Libraries/raw/master/2022.3.16.zip to M:\SteamLibrary\steamapps\common\House Party\MelonLoader\Dependencies\Il2CppAssemblyGenerator\UnityDependencies_2022.3.16.zip
[21:00:25.567] [Il2CppAssemblyGenerator] System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at MelonLoader.Il2CppAssemblyGenerator.Extensions.DownloadFile(HttpClient client, String url, String dest) in D:\a\MelonLoader\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Extensions.cs:line 10
   at MelonLoader.Il2CppAssemblyGenerator.FileHandler.Download(String url, String destination) in D:\a\MelonLoader\MelonLoader\Dependencies\Il2CppAssemblyGenerator\FileHandler.cs:line 34
[21:00:25.568] [INTERNAL FAILURE] Failed to Download UnityDependencies!

[Latest.log](https://github.com/LavaGang/MelonLoader/files/13760110/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by RinLovesYou** [comment]
That unity version was released just a few days ago. Games update fast these days. @DragonPlayerX

**Comment by DragonPlayerX** [comment]
Should be available now.

**Comment by RinLovesYou** [comment]
Thanks mate
