### ISSUE TITLE
[Bug]: Unity 2022.3.19 UnityDependencies Download Error.

### ISSUE THREAD

**Issue by Jamjardavies** [LavaGang/MelonLoader#616]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

Tries downloading the Unity Dependencies files for a Unity version but fails.

```
[23:53:21.944] [Il2CppAssemblyGenerator] Downloading https://github.com/LavaGang/Unity-Runtime-Libraries/raw/master/2022.3.19.zip to C:\Program Files (x86)\Steam\steamapps\common\Idle Slayer\MelonLoader\Dependencies\Il2CppAssemblyGenerator\UnityDependencies_2022.3.19.zip
[23:53:22.202] [Il2CppAssemblyGenerator] System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)
 ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.GetStreamAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at MelonLoader.Il2CppAssemblyGenerator.Extensions.DownloadFile(HttpClient client, String url, String dest) in D:\a\MelonLoader\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Extensions.cs:line 10
   at MelonLoader.Il2CppAssemblyGenerator.FileHandler.Download(String url, String destination) in D:\a\MelonLoader\MelonLoader\Dependencies\Il2CppAssemblyGenerator\FileHandler.cs:line 34
```

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by RinLovesYou** [comment]
@DragonPlayerX

**Comment by DragonPlayerX** [comment]
Just uploaded the file, should work now

**Comment by RinLovesYou** [comment]
Thanks mate
