### ISSUE TITLE
[Bug]: Idle Slayer game causes Class::Init signatures have been exhausted, using a substitute

### ISSUE THREAD

**Issue by Jamjardavies** [LavaGang/MelonLoader#639]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

Recently updated Idle Slayer (free game) on Steam (MelonLoader worked before the update) and now getting the following error:
[Latest.log](https://github.com/LavaGang/MelonLoader/files/14920376/Latest.log)

There are no mods, and have tried a fresh install of both the game AND MelonLoader.

Note: The following isn't shown in the log file, but appears on the console output.
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Il2CppInterop.Runtime.Injection.InjectorHelpers.hkGetTypeInfoFromTypeDefinitionIndex(Int32)
   at Il2CppInterop.Runtime.Injection.InjectorHelpers.hkClassFromName(Il2CppInterop.Runtime.Runtime.Il2CppImage*, IntPtr, IntPtr)
   at Il2CppInterop.Runtime.IL2CPP.il2cpp_class_from_name(IntPtr, System.String, System.String)
   at Il2CppInterop.Runtime.IL2CPP.GetIl2CppClass(System.String, System.String, System.String)
   at Il2CppSystem.Void..cctor()
   at System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(System.RuntimeTypeHandle)
   at Il2CppInterop.Runtime.Il2CppClassPointerStore`1[[Il2CppSystem.Void, Il2Cppmscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null]]..cctor()
   at Il2CppInterop.Runtime.Injection.ClassInjector.ConvertStaticMethod(VoidCtorDelegate, System.String, Il2CppInterop.Runtime.Runtime.VersionSpecific.Class.INativeClassStruct)
   at Il2CppInterop.Runtime.Injection.ClassInjector.RegisterTypeInIl2Cpp(System.Type, Il2CppInterop.Runtime.Injection.RegisterTypeOptions)
   at Il2CppInterop.Runtime.DelegateSupport.ConvertDelegate[[System.__Canon, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]](System.Delegate)
   at UnityEngine.Events.UnityAction`2[[UnityEngine.SceneManagement.Scene, UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null],[UnityEngine.SceneManagement.LoadSceneMode, UnityEngine.CoreModule, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null]].op_Implicit(System.Action`2<UnityEngine.SceneManagement.Scene,UnityEngine.SceneManagement.LoadSceneMode>)
   at MelonLoader.Support.SceneHandler.Init()
   at MelonLoader.Support.Main.Initialize(MelonLoader.ISupportModule_From)
   at System.RuntimeMethodHandle.InvokeMethod(System.Object, System.Span`1<System.Object> ByRef, System.Signature, Boolean, Boolean)
   at System.Reflection.RuntimeMethodInfo.Invoke(System.Object, System.Reflection.BindingFlags, System.Reflection.Binder, System.Object[], System.Globalization.CultureInfo)
   at System.Reflection.MethodBase.Invoke(System.Object, System.Object[])
   at MelonLoader.SupportModule.LoadInterface(System.String)
   at MelonLoader.SupportModule.Setup()
   at MelonLoader.Core.Start()
   at MelonLoader.NativeHost.NativeEntryPoint.Start()
```

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by SamboyCoding** [comment]
This should probably be opened in the [Il2CppInterop](https://github.com/bepInEx/il2cppinterop) repo, as it's likely a bug on their side, not ours.

**Comment by slxdy** [comment]
This issue can be closed as it does not belong to MelonLoader

**Comment by Jamjardavies** [comment]
It seems it's now working again, so will close.

**Comment by NachoSlayer** [comment]
This has also been happening with every game Melon Loader tries to inject. I have been getting this with BTD6 

"[Il2CppInterop] Class::Init signatures have been exhausted, using a substitute!
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. ...
at Il2CppInterop.Runtime.Injection.Hooks.GenericMethod_GetMethod_Hook.Hook"
