### ISSUE TITLE
[Bug]: Internal CLR Error (0x80131506)

### ISSUE THREAD

**Issue by afunniguy** [LavaGang/MelonLoader#663]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [x] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [x] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

The game had an update and when trying to load up the game, it can get through everything but when it comes to opening the game, it shows an error that doesn't even get logged and closes. I've tried everything from changing the game's path, trying different versions of melonloader, etc but to no luck. Does anyone happen to have any solutions?

[Latest.log](https://github.com/user-attachments/files/15832023/Latest.log)

-- Error that doesn't show in Log --
Fatal error. Internal CLR error. (0x80131506)
Repeat 2 times:
at 112CppInterop.Runtime.IL2CPP.i12cpp_runtime_invoke(IntPtr, IntPtr, Void**, IntPtr ByRef)
at UnityEngine.GameObject.AddComponent (I12CppSystem.Type)
at MelonLoader. Support. SM_Component.Create()
at MelonLoader.Support.Main. Initialize (MelonLoader. ISupportModule_From)
at System.RuntimeMethodHandle. InvokeMethod (System.Object, System. Span` 1<System.Object> ByRef, System.Signature, Boole an, Boolean)
at System.Reflection.RuntimeMethodInfo.Invoke (System.Object, System.Reflection.BindingFlags, System.Reflection.Binder , System.Object[], System.Globalization. CultureInfo)
at System.Reflection.MethodBase. Invoke(System.Object, System.Object[])
at MelonLoader. Support Module.LoadInterface (System.String)
at MelonLoader. SupportModule.Setup()
at MelonLoader.Core.Start()
at MelonLoader.NativeHost.NativeEntryPoint.Start()

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by SamboyCoding** [comment]
Il2CppInterop issue, likely unity 2022.3 support incomplete. There is something to be done our side RE the EndOfStreamException at the top, so this should stay open.

**Comment by HerpDerpinstine** [comment]
Please retest with this latest [alpha-development nightly](https://nightly.link/LavaGang/MelonLoader/workflows/build/alpha-development/MelonLoader.Windows.x64.CI.Release.zip) build.

**Comment by afunniguy** [comment]
the game opens fine now.
