### ISSUE TITLE
[Error]: No Support Module Loaded!

### ISSUE THREAD

**Issue by melonloader-cell** [LavaGang/MelonLoader#674]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

So I am trying to load mods but they won't load, they say "Mod Loaded" but do not work. I understand that I haven't any mods in this latest.log but that is not the issue. I have tried very well known mods and even my own, it will say that the mod loaded but nothing else then it will display the error codes. Even it does not show the start screen customization in UserData folder, I think it is supposed to. It did however pull the game DLLs as seen in the console and in my folder.

[17:23:23.059] ------------------------------
[17:23:23.083] MelonLoader v0.6.2 Open-Beta
[17:23:23.084] OS: Windows 11
[17:23:23.084] Hash Code: 2AD1478D8329B7784C949251EAF68C4C50E2FE9DA6CBB4BDF1DCD43E9026C63C
[17:23:23.084] ------------------------------
[17:23:23.084] Game Type: Il2cpp
[17:23:23.084] Game Arch: x64

[17:23:32.370] Preferences Loaded!

[17:23:33.472] Loading UserLibss from 'C:\Users\...

[17:23:33.477] Loading Plugins from 'C:\Users\...
[17:23:33.478] 0 Plugins loaded.
[17:23:35.790] Loading Il2CppAssemblyGenerator...
[17:23:35.812] [Il2CppAssemblyGenerator] Contacting RemoteAPI...
[17:23:36.031] [Il2CppAssemblyGenerator] Game Not Found on RemoteAPI Host (https://api.melonloader.com/api/v1/game/...)
[17:23:36.031] [Il2CppAssemblyGenerator] RemoteAPI.DumperVersion = null
[17:23:36.031] [Il2CppAssemblyGenerator] RemoteAPI.ObfuscationRegex = null
[17:23:36.031] [Il2CppAssemblyGenerator] RemoteAPI.MappingURL = null
[17:23:36.032] [Il2CppAssemblyGenerator] RemoteAPI.MappingFileSHA512 = null
[17:23:36.056] [Il2CppAssemblyGenerator] Using Dumper Version: 2022.1.0-pre-release.13
[17:23:36.056] [Il2CppAssemblyGenerator] Using Il2CppInterop Version = 1.4.5
[17:23:36.057] [Il2CppAssemblyGenerator] Using Unity Dependencies Version = 2022.3.25
[17:23:36.057] [Il2CppAssemblyGenerator] Using Deobfuscation Regex = null
[17:23:36.058] [Il2CppAssemblyGenerator] Downloading Cpp2IL...
[17:23:36.058] [Il2CppAssemblyGenerator] Downloading https://github.com/SamboyCoding/Cpp2IL/releases/download/2022.1.0-pre-release.13/Cpp2IL-2022.1.0-pre-release.13-Windows-Netframework472.zip to C:\Users\...\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL_2022.1.0-pre-release.13.zip
[17:23:36.630] [Il2CppAssemblyGenerator] Processing Cpp2IL...
[17:23:36.631] [Il2CppAssemblyGenerator] Creating Directory C:\Users\...\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL
[17:23:36.632] [Il2CppAssemblyGenerator] Extracting C:\Users\...\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL_2022.1.0-pre-release.13.zip to C:\Users\...\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL
[17:23:36.701] [Il2CppAssemblyGenerator] Downloading UnityDependencies...
[17:23:36.702] [Il2CppAssemblyGenerator] Downloading https://github.com/LavaGang/Unity-Runtime-Libraries/raw/master/2022.3.25.zip to C:\Users\...\MelonLoader\Dependencies\Il2CppAssemblyGenerator\UnityDependencies_2022.3.25.zip
[17:23:37.161] [Il2CppAssemblyGenerator] Processing UnityDependencies...
[17:23:37.161] [Il2CppAssemblyGenerator] Creating Directory C:\Users\...\MelonLoader\Dependencies\Il2CppAssemblyGenerator\UnityDependencies
[17:23:37.161] [Il2CppAssemblyGenerator] Extracting C:\Users\...\MelonLoader\Dependencies\Il2CppAssemblyGenerator\UnityDependencies_2022.3.25.zip to C:\Users\...\MelonLoader\Dependencies\Il2CppAssemblyGenerator\UnityDependencies
[17:23:37.231] [Il2CppAssemblyGenerator] Checking GameAssembly...
[17:23:37.870] [Il2CppAssemblyGenerator] Assembly Generation Needed!
[17:23:37.880] [Il2CppAssemblyGenerator] Executing Cpp2IL...
[17:23:37.881] [Il2CppAssemblyGenerator] "C:\Users\...\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL\Cpp2IL.exe" --game-path "C:\Users\..." --exe-name "xxx" --use-processor attributeinjector --output-as dummydll
[17:23:37.956] TODO: SetProcessId(29232)
[17:23:38.014] [Il2CppAssemblyGenerator] ===Cpp2IL by Samboy063===
[17:23:38.014] [Il2CppAssemblyGenerator] A Tool to Reverse Unity's "il2cpp" Build Process.
[17:23:38.014] [Il2CppAssemblyGenerator] Version 2022.1.0-pre-release.13+3d6a81f9ff4c081902a55eac84643628d608bbaf
[17:23:38.014] [Il2CppAssemblyGenerator] 
[17:23:38.026] [Il2CppAssemblyGenerator] [Warn] [Program] NO_COLOR set, disabling ANSI color codes as you requested.
[17:23:38.026] [Il2CppAssemblyGenerator] [Info] [Program] Running on Win32NT
[17:23:38.112] [Il2CppAssemblyGenerator] [Info] [Plugins] Loading plugins from C:\Users\...\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL\Plugins...
[17:23:38.149] [Il2CppAssemblyGenerator] [Info] [Plugins] Using Plugin: Cpp2IL Built-In
[17:23:38.155] [Il2CppAssemblyGenerator] [Info] [Program] Determined game's unity version to be 2022.3.25a0
[17:23:38.384] [Il2CppAssemblyGenerator] [Info] [Library] Initializing Metadata...
[17:23:38.386] [Il2CppAssemblyGenerator] [Info] [Library] 	Using actual IL2CPP Metadata version 29.1
[17:23:38.777] [Il2CppAssemblyGenerator] [Info] [Library] Initialized Metadata in 393ms
[17:23:38.779] [Il2CppAssemblyGenerator] [Info] [Library] Using binary type Portable Executable (from LibCpp2IL)
[17:23:38.779] [Il2CppAssemblyGenerator] [Info] [Library] Searching Binary for Required Data...
[17:23:39.714] [Il2CppAssemblyGenerator] [Info] [Library] Got Binary codereg: 0x18774C2F0, metareg: 0x187ECF2D0 in 935ms.
[17:23:39.714] [Il2CppAssemblyGenerator] [Info] [Library] Initializing Binary...
[17:23:39.877] [Il2CppAssemblyGenerator] [Info] [Library] Initialized Binary in 162ms
[17:23:40.066] [Il2CppAssemblyGenerator] [Info] [Library] Mapping pointers to Il2CppMethodDefinitions...Processed 407084 OK (189ms)
[17:23:40.082] [Il2CppAssemblyGenerator] [Info] [Program] Creating application model...
[17:23:42.680] [Il2CppAssemblyGenerator] [Info] [Program] Application model created in 2599ms
[17:23:42.680] [Il2CppAssemblyGenerator] [Info] [Program] Pre-processing processing layers...
[17:23:42.682] [Il2CppAssemblyGenerator] [Info] [Program]     Attribute Injector...
[17:23:42.682] [Il2CppAssemblyGenerator] [Info] [Program]     Attribute Injector finished in 0ms
[17:23:42.683] [Il2CppAssemblyGenerator] [Info] [Program] Invoking processing layers...
[17:23:42.683] [Il2CppAssemblyGenerator] [Info] [Program]     Attribute Injector...
[17:23:43.380] [Il2CppAssemblyGenerator] [Info] [Program]     Attribute Injector finished in 698.3502ms
[17:23:43.380] [Il2CppAssemblyGenerator] [Info] [Program] Outputting as DLL output format for backwards compatibility. to C:\Users\...\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL\cpp2il_out...
[17:23:49.534] [Il2CppAssemblyGenerator] [Info] [Program] Finished outputting in 6154.4126ms
[17:23:49.535] [Il2CppAssemblyGenerator] [Info] [Program] Done. Total execution time: 11377.9992ms
[17:23:49.981] TODO: SetProcessId(0)
[17:23:49.982] [Il2CppAssemblyGenerator] Reading dumped assemblies for interop generation...
[17:23:50.027] [Il2CppAssemblyGenerator] Generating Interop Assemblies...
[17:23:50.034] [Il2CppAssemblyGenerator] Reading assemblies...
[17:23:51.228] [Il2CppAssemblyGenerator] Done in 00:00:01.1933887
[17:23:51.228] [Il2CppAssemblyGenerator] Reading unity assemblies...
[17:23:51.240] [Il2CppAssemblyGenerator] Done in 00:00:00.0113492
[17:23:51.240] [Il2CppAssemblyGenerator] Creating rewrite assemblies...
[17:23:51.264] [Il2CppAssemblyGenerator] Done in 00:00:00.0228633
[17:23:51.264] [Il2CppAssemblyGenerator] Computing renames...
[17:23:51.321] [Il2CppAssemblyGenerator] Done in 00:00:00.0565570
[17:23:51.322] [Il2CppAssemblyGenerator] Creating typedefs...
[17:23:51.404] [Il2CppAssemblyGenerator] Done in 00:00:00.0821681
[17:23:51.404] [Il2CppAssemblyGenerator] Computing struct blittability...
[17:23:51.553] [Il2CppAssemblyGenerator] Done in 00:00:00.1480087
[17:23:51.553] [Il2CppAssemblyGenerator] Filling typedefs...
[17:23:51.635] [Il2CppAssemblyGenerator] Done in 00:00:00.0819659
[17:23:51.636] [Il2CppAssemblyGenerator] Filling generic constraints...
[17:23:51.643] [Il2CppAssemblyGenerator] Done in 00:00:00.0068753
[17:23:51.644] [Il2CppAssemblyGenerator] Creating members...
[17:23:56.698] [Il2CppAssemblyGenerator] Done in 00:00:05.0541952
[17:23:56.699] [Il2CppAssemblyGenerator] Scanning method cross-references...
[17:23:59.498] [Il2CppAssemblyGenerator] Done in 00:00:02.7984570
[17:23:59.498] [Il2CppAssemblyGenerator] Finalizing method declarations...
[17:24:08.299] [Il2CppAssemblyGenerator] Done in 00:00:08.8009281
[17:24:08.308] [Il2CppAssemblyGenerator] 95 total potentially dead methods
[17:24:08.310] [Il2CppAssemblyGenerator] Filling method parameters...
[17:24:09.819] [Il2CppAssemblyGenerator] Done in 00:00:01.5074548
[17:24:09.819] [Il2CppAssemblyGenerator] Creating static constructors...
[17:24:11.712] [Il2CppAssemblyGenerator] Done in 00:00:01.8924567
[17:24:11.712] [Il2CppAssemblyGenerator] Creating value type fields...
[17:24:12.216] [Il2CppAssemblyGenerator] Done in 00:00:00.5034549
[17:24:12.216] [Il2CppAssemblyGenerator] Creating enums...
[17:24:12.400] [Il2CppAssemblyGenerator] Done in 00:00:00.1834644
[17:24:12.401] [Il2CppAssemblyGenerator] Creating IntPtr constructors...
[17:24:12.721] [Il2CppAssemblyGenerator] Done in 00:00:00.3201980
[17:24:12.721] [Il2CppAssemblyGenerator] Creating non-blittable struct constructors...
[17:24:12.755] [Il2CppAssemblyGenerator] Done in 00:00:00.0337300
[17:24:12.756] [Il2CppAssemblyGenerator] Creating generic method static constructors...
[17:24:12.887] [Il2CppAssemblyGenerator] Done in 00:00:00.1308758
[17:24:12.887] [Il2CppAssemblyGenerator] Creating field accessors...
[17:24:14.738] [Il2CppAssemblyGenerator] Done in 00:00:01.8502022
[17:24:14.738] [Il2CppAssemblyGenerator] Filling methods...
[17:24:25.370] [Il2CppAssemblyGenerator] Done in 00:00:10.6315109
[17:24:25.370] [Il2CppAssemblyGenerator] Generating implicit conversions...
[17:24:25.412] [Il2CppAssemblyGenerator] Done in 00:00:00.0412891
[17:24:25.412] [Il2CppAssemblyGenerator] Creating properties...
[17:24:25.585] [Il2CppAssemblyGenerator] Done in 00:00:00.1729682
[17:24:25.585] [Il2CppAssemblyGenerator] Unstripping types...
[17:24:25.641] [Il2CppAssemblyGenerator] Done in 00:00:00.0557262
[17:24:25.642] [Il2CppAssemblyGenerator] Unstripping fields...
[17:24:25.649] [Il2CppAssemblyGenerator] Restored 504 fields
[17:24:25.649] [Il2CppAssemblyGenerator] Failed to restore 1 fields
[17:24:25.649] [Il2CppAssemblyGenerator] Done in 00:00:00.0069927
[17:24:25.649] [Il2CppAssemblyGenerator] Unstripping methods...
[17:24:26.162] [Il2CppAssemblyGenerator] Restored 13549 methods
[17:24:26.162] [Il2CppAssemblyGenerator] Failed to restore 964 methods
[17:24:26.163] [Il2CppAssemblyGenerator] Done in 00:00:00.5135831
[17:24:26.163] [Il2CppAssemblyGenerator] Unstripping method bodies...
[17:24:26.541] [Il2CppAssemblyGenerator] IL unstrip statistics: 6889 successful, 1863 failed
[17:24:26.541] [Il2CppAssemblyGenerator] Done in 00:00:00.3772593
[17:24:26.541] [Il2CppAssemblyGenerator] Writing xref cache...
[17:24:33.128] [Il2CppAssemblyGenerator] Done in 00:00:06.5864477
[17:24:33.128] [Il2CppAssemblyGenerator] Writing assemblies...
[17:24:35.774] [Il2CppAssemblyGenerator] Done in 00:00:02.6450342
[17:24:35.774] [Il2CppAssemblyGenerator] Writing method pointer map...
[17:24:35.882] [Il2CppAssemblyGenerator] Done in 00:00:00.1078489
[17:24:35.882] [Il2CppAssemblyGenerator] Done!
[17:24:35.889] [Il2CppAssemblyGenerator] Cleaning up...
[17:24:35.889] [Il2CppAssemblyGenerator] Interop Generation Complete!
[17:24:35.890] [Il2CppAssemblyGenerator] Moving Assembly-CSharp-firstpass.dll
[17:24:35.891] [Il2CppAssemblyGenerator] Moving Assembly-CSharp.dll
[17:24:35.891] [Il2CppAssemblyGenerator] Moving Il2CppAIToASE.dll
[17:24:35.892] [Il2CppAssemblyGenerator] Moving Il2CppAmplifyImpostors.dll
[17:24:35.892] [Il2CppAssemblyGenerator] Moving Il2CppAsmDef.dll
[17:24:35.893] [Il2CppAssemblyGenerator] Moving Il2CppBehaviorDesigner.Runtime.dll
[17:24:35.893] [Il2CppAssemblyGenerator] Moving Il2CppBoxophobic.AtmosphericHeightFog.Runtime.dll
[17:24:35.893] [Il2CppAssemblyGenerator] Moving Il2CppBoxophobic.TheVehetationEngine.Runtime.dll
[17:24:35.894] [Il2CppAssemblyGenerator] Moving Il2CppBoxophobic.Utils.Scripts.dll
[17:24:35.894] [Il2CppAssemblyGenerator] Moving Il2CppChartEditor.dll
[17:24:35.895] [Il2CppAssemblyGenerator] Moving Il2CppCinemachine.dll
[17:24:35.895] [Il2CppAssemblyGenerator] Moving Il2CppDelaunayER.dll
[17:24:35.896] [Il2CppAssemblyGenerator] Moving Il2CppDOTween.dll
[17:24:35.896] [Il2CppAssemblyGenerator] Moving Il2CppEasyRoads3Dv3.dll
[17:24:35.897] [Il2CppAssemblyGenerator] Moving Il2CppElringus.UnityGoogleDrive.Runtime.dll
[17:24:35.897] [Il2CppAssemblyGenerator] Moving Il2CppEOS.dll
[17:24:35.897] [Il2CppAssemblyGenerator] Moving Il2CppGdkUtilities.dll
[17:24:35.898] [Il2CppAssemblyGenerator] Moving Il2CppGPUInstancer.dll
[17:24:35.898] [Il2CppAssemblyGenerator] Moving Il2CppHBAO.Runtime.dll
[17:24:35.898] [Il2CppAssemblyGenerator] Moving Il2CppJBooth.MicroSplat.Core.dll
[17:24:35.899] [Il2CppAssemblyGenerator] Moving Il2CppM2H_UnityExtensions.dll
[17:24:35.899] [Il2CppAssemblyGenerator] Moving Il2CppMono.Security.dll
[17:24:35.900] [Il2CppAssemblyGenerator] Moving Il2Cppmscorlib.dll
[17:24:35.900] [Il2CppAssemblyGenerator] Moving Il2CppNewtonsoft.Json.dll
[17:24:35.900] [Il2CppAssemblyGenerator] Moving Il2CppPerfectCulling.dll
[17:24:35.900] [Il2CppAssemblyGenerator] Moving Il2CppPhoton3Unity3D.dll
[17:24:35.901] [Il2CppAssemblyGenerator] Moving Il2CppPhotonChat.dll
[17:24:35.901] [Il2CppAssemblyGenerator] Moving Il2CppPhotonRealtime.dll
[17:24:35.901] [Il2CppAssemblyGenerator] Moving Il2CppPhotonUnityNetworking.dll
[17:24:35.902] [Il2CppAssemblyGenerator] Moving Il2CppPhotonUnityNetworking.Utilities.dll
[17:24:35.902] [Il2CppAssemblyGenerator] Moving Il2CppPlayFab.dll
[17:24:35.904] [Il2CppAssemblyGenerator] Moving Il2CppPlayFabPartySDK.dll
[17:24:35.905] [Il2CppAssemblyGenerator] Moving Il2CppRewired_Core.dll
[17:24:35.905] [Il2CppAssemblyGenerator] Moving Il2CppRewired_Windows.dll
[17:24:35.906] [Il2CppAssemblyGenerator] Moving Il2CppRewired_Windows_Functions.dll
[17:24:35.906] [Il2CppAssemblyGenerator] Moving Il2CppSerializedDictionaryAsmDef.dll
[17:24:35.906] [Il2CppAssemblyGenerator] Moving Il2CppSystem.Configuration.dll
[17:24:35.907] [Il2CppAssemblyGenerator] Moving Il2CppSystem.Core.dll
[17:24:35.907] [Il2CppAssemblyGenerator] Moving Il2CppSystem.Data.dll
[17:24:35.907] [Il2CppAssemblyGenerator] Moving Il2CppSystem.dll
[17:24:35.908] [Il2CppAssemblyGenerator] Moving Il2CppSystem.Drawing.dll
[17:24:35.908] [Il2CppAssemblyGenerator] Moving Il2CppSystem.Numerics.dll
[17:24:35.909] [Il2CppAssemblyGenerator] Moving Il2CppSystem.Runtime.Serialization.dll
[17:24:35.909] [Il2CppAssemblyGenerator] Moving Il2CppSystem.Xml.dll
[17:24:35.909] [Il2CppAssemblyGenerator] Moving Il2CppSystem.Xml.Linq.dll
[17:24:35.911] [Il2CppAssemblyGenerator] Moving Il2CppXGamingRuntime.dll
[17:24:35.911] [Il2CppAssemblyGenerator] Moving Il2Cpp__Generated.dll
[17:24:35.911] [Il2CppAssemblyGenerator] Moving MethodAddressToToken.db
[17:24:35.912] [Il2CppAssemblyGenerator] Moving MethodXrefScanCache.db
[17:24:35.912] [Il2CppAssemblyGenerator] Moving Unity.Addressables.dll
[17:24:35.912] [Il2CppAssemblyGenerator] Moving Unity.AI.Navigation.dll
[17:24:35.913] [Il2CppAssemblyGenerator] Moving Unity.Burst.dll
[17:24:35.913] [Il2CppAssemblyGenerator] Moving Unity.Burst.Unsafe.dll
[17:24:35.914] [Il2CppAssemblyGenerator] Moving Unity.Collections.dll
[17:24:35.914] [Il2CppAssemblyGenerator] Moving Unity.Collections.LowLevel.ILSupport.dll
[17:24:35.914] [Il2CppAssemblyGenerator] Moving Unity.InternalAPIEngineBridge.024.dll
[17:24:35.915] [Il2CppAssemblyGenerator] Moving Unity.Mathematics.dll
[17:24:35.915] [Il2CppAssemblyGenerator] Moving Unity.Polybrush.dll
[17:24:35.916] [Il2CppAssemblyGenerator] Moving Unity.Postprocessing.Runtime.dll
[17:24:35.916] [Il2CppAssemblyGenerator] Moving Unity.Profiling.Core.dll
[17:24:35.916] [Il2CppAssemblyGenerator] Moving Unity.ResourceManager.dll
[17:24:35.917] [Il2CppAssemblyGenerator] Moving Unity.Splines.dll
[17:24:35.917] [Il2CppAssemblyGenerator] Moving Unity.TextMeshPro.dll
[17:24:35.918] [Il2CppAssemblyGenerator] Moving Unity.Timeline.dll
[17:24:35.920] [Il2CppAssemblyGenerator] Moving UnityEngine.AccessibilityModule.dll
[17:24:35.921] [Il2CppAssemblyGenerator] Moving UnityEngine.AIModule.dll
[17:24:35.921] [Il2CppAssemblyGenerator] Moving UnityEngine.AndroidJNIModule.dll
[17:24:35.921] [Il2CppAssemblyGenerator] Moving UnityEngine.AnimationModule.dll
[17:24:35.922] [Il2CppAssemblyGenerator] Moving UnityEngine.ARModule.dll
[17:24:35.922] [Il2CppAssemblyGenerator] Moving UnityEngine.AssetBundleModule.dll
[17:24:35.923] [Il2CppAssemblyGenerator] Moving UnityEngine.AudioModule.dll
[17:24:35.923] [Il2CppAssemblyGenerator] Moving UnityEngine.ClothModule.dll
[17:24:35.923] [Il2CppAssemblyGenerator] Moving UnityEngine.ClusterInputModule.dll
[17:24:35.923] [Il2CppAssemblyGenerator] Moving UnityEngine.ClusterRendererModule.dll
[17:24:35.924] [Il2CppAssemblyGenerator] Moving UnityEngine.ContentLoadModule.dll
[17:24:35.924] [Il2CppAssemblyGenerator] Moving UnityEngine.CoreModule.dll
[17:24:35.924] [Il2CppAssemblyGenerator] Moving UnityEngine.CrashReportingModule.dll
[17:24:35.925] [Il2CppAssemblyGenerator] Moving UnityEngine.DirectorModule.dll
[17:24:35.925] [Il2CppAssemblyGenerator] Moving UnityEngine.dll
[17:24:35.926] [Il2CppAssemblyGenerator] Moving UnityEngine.DSPGraphModule.dll
[17:24:35.926] [Il2CppAssemblyGenerator] Moving UnityEngine.GameCenterModule.dll
[17:24:35.926] [Il2CppAssemblyGenerator] Moving UnityEngine.GIModule.dll
[17:24:35.927] [Il2CppAssemblyGenerator] Moving UnityEngine.GridModule.dll
[17:24:35.927] [Il2CppAssemblyGenerator] Moving UnityEngine.HotReloadModule.dll
[17:24:35.927] [Il2CppAssemblyGenerator] Moving UnityEngine.ImageConversionModule.dll
[17:24:35.928] [Il2CppAssemblyGenerator] Moving UnityEngine.IMGUIModule.dll
[17:24:35.928] [Il2CppAssemblyGenerator] Moving UnityEngine.InputLegacyModule.dll
[17:24:35.928] [Il2CppAssemblyGenerator] Moving UnityEngine.InputModule.dll
[17:24:35.929] [Il2CppAssemblyGenerator] Moving UnityEngine.JSONSerializeModule.dll
[17:24:35.929] [Il2CppAssemblyGenerator] Moving UnityEngine.LocalizationModule.dll
[17:24:35.929] [Il2CppAssemblyGenerator] Moving UnityEngine.NVIDIAModule.dll
[17:24:35.930] [Il2CppAssemblyGenerator] Moving UnityEngine.ParticleSystemModule.dll
[17:24:35.930] [Il2CppAssemblyGenerator] Moving UnityEngine.PerformanceReportingModule.dll
[17:24:35.930] [Il2CppAssemblyGenerator] Moving UnityEngine.Physics2DModule.dll
[17:24:35.931] [Il2CppAssemblyGenerator] Moving UnityEngine.PhysicsModule.dll
[17:24:35.931] [Il2CppAssemblyGenerator] Moving UnityEngine.ProfilerModule.dll
[17:24:35.931] [Il2CppAssemblyGenerator] Moving UnityEngine.PropertiesModule.dll
[17:24:35.931] [Il2CppAssemblyGenerator] Moving UnityEngine.RuntimeInitializeOnLoadManagerInitializerModule.dll
[17:24:35.932] [Il2CppAssemblyGenerator] Moving UnityEngine.ScreenCaptureModule.dll
[17:24:35.932] [Il2CppAssemblyGenerator] Moving UnityEngine.SharedInternalsModule.dll
[17:24:35.933] [Il2CppAssemblyGenerator] Moving UnityEngine.SpriteMaskModule.dll
[17:24:35.933] [Il2CppAssemblyGenerator] Moving UnityEngine.SpriteShapeModule.dll
[17:24:35.933] [Il2CppAssemblyGenerator] Moving UnityEngine.StreamingModule.dll
[17:24:35.934] [Il2CppAssemblyGenerator] Moving UnityEngine.SubstanceModule.dll
[17:24:35.936] [Il2CppAssemblyGenerator] Moving UnityEngine.SubsystemsModule.dll
[17:24:35.936] [Il2CppAssemblyGenerator] Moving UnityEngine.TerrainModule.dll
[17:24:35.936] [Il2CppAssemblyGenerator] Moving UnityEngine.TerrainPhysicsModule.dll
[17:24:35.937] [Il2CppAssemblyGenerator] Moving UnityEngine.TextCoreFontEngineModule.dll
[17:24:35.937] [Il2CppAssemblyGenerator] Moving UnityEngine.TextCoreTextEngineModule.dll
[17:24:35.937] [Il2CppAssemblyGenerator] Moving UnityEngine.TextRenderingModule.dll
[17:24:35.938] [Il2CppAssemblyGenerator] Moving UnityEngine.TilemapModule.dll
[17:24:35.938] [Il2CppAssemblyGenerator] Moving UnityEngine.TLSModule.dll
[17:24:35.938] [Il2CppAssemblyGenerator] Moving UnityEngine.UI.dll
[17:24:35.939] [Il2CppAssemblyGenerator] Moving UnityEngine.UIElementsModule.dll
[17:24:35.939] [Il2CppAssemblyGenerator] Moving UnityEngine.UIModule.dll
[17:24:35.939] [Il2CppAssemblyGenerator] Moving UnityEngine.UmbraModule.dll
[17:24:35.939] [Il2CppAssemblyGenerator] Moving UnityEngine.UnityAnalyticsCommonModule.dll
[17:24:35.940] [Il2CppAssemblyGenerator] Moving UnityEngine.UnityAnalyticsModule.dll
[17:24:35.941] [Il2CppAssemblyGenerator] Moving UnityEngine.UnityConnectModule.dll
[17:24:35.941] [Il2CppAssemblyGenerator] Moving UnityEngine.UnityCurlModule.dll
[17:24:35.941] [Il2CppAssemblyGenerator] Moving UnityEngine.UnityTestProtocolModule.dll
[17:24:35.942] [Il2CppAssemblyGenerator] Moving UnityEngine.UnityWebRequestAssetBundleModule.dll
[17:24:35.942] [Il2CppAssemblyGenerator] Moving UnityEngine.UnityWebRequestAudioModule.dll
[17:24:35.942] [Il2CppAssemblyGenerator] Moving UnityEngine.UnityWebRequestModule.dll
[17:24:35.943] [Il2CppAssemblyGenerator] Moving UnityEngine.UnityWebRequestTextureModule.dll
[17:24:35.943] [Il2CppAssemblyGenerator] Moving UnityEngine.UnityWebRequestWWWModule.dll
[17:24:35.943] [Il2CppAssemblyGenerator] Moving UnityEngine.VehiclesModule.dll
[17:24:35.943] [Il2CppAssemblyGenerator] Moving UnityEngine.VFXModule.dll
[17:24:35.944] [Il2CppAssemblyGenerator] Moving UnityEngine.VideoModule.dll
[17:24:35.944] [Il2CppAssemblyGenerator] Moving UnityEngine.VirtualTexturingModule.dll
[17:24:35.945] [Il2CppAssemblyGenerator] Moving UnityEngine.VRModule.dll
[17:24:35.945] [Il2CppAssemblyGenerator] Moving UnityEngine.WindModule.dll
[17:24:35.945] [Il2CppAssemblyGenerator] Moving UnityEngine.XRModule.dll
[17:24:35.948] [Il2CppAssemblyGenerator] Assembly Generation Successful!

[17:24:35.952] Loading Mods from 'C:\Users\...\Mods'...
[17:24:35.952] 0 Mods loaded.

[17:24:38.668] SceneManager.sceneLoaded override failed: System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at Il2CppInterop.Runtime.Injection.InjectorHelpers.FindGetTypeInfoFromTypeDefinitionIndex(Boolean forceICallMethod) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/InjectorHelpers.cs:line 269
   at Il2CppInterop.Runtime.Injection.InjectorHelpers.Setup() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/InjectorHelpers.cs:line 68
   at Il2CppInterop.Runtime.Injection.ClassInjector.RegisterTypeInIl2Cpp(Type type, RegisterTypeOptions options) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/ClassInjector.cs:line 188
   at Il2CppInterop.Runtime.DelegateSupport.ConvertDelegate[TIl2Cpp](Delegate delegate) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/DelegateSupport.cs:line 242
   at UnityEngine.Events.UnityAction`2.op_Implicit(Action`2 )
   at MelonLoader.Support.SceneHandler.Init() in D:\a\MelonLoader\MelonLoader\Dependencies\SupportModules\SceneHandler.cs:line 26
[17:24:38.672] SceneManager.sceneUnloaded override failed: System.InvalidOperationException: Sequence contains more than one element
   at System.Linq.ThrowHelper.ThrowMoreThanOneElementException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Boolean& found)
   at Il2CppInterop.Runtime.Injection.InjectorHelpers.FindGetTypeInfoFromTypeDefinitionIndex(Boolean forceICallMethod) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/InjectorHelpers.cs:line 269
   at Il2CppInterop.Runtime.Injection.InjectorHelpers.Setup() in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/InjectorHelpers.cs:line 68
   at Il2CppInterop.Runtime.Injection.ClassInjector.RegisterTypeInIl2Cpp(Type type, RegisterTypeOptions options) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/ClassInjector.cs:line 188
   at Il2CppInterop.Runtime.DelegateSupport.ConvertDelegate[TIl2Cpp](Delegate delegate) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/DelegateSupport.cs:line 242
   at UnityEngine.Events.UnityAction`1.op_Implicit(Action`1 )
   at MelonLoader.Support.SceneHandler.Init() in D:\a\MelonLoader\MelonLoader\Dependencies\SupportModules\SceneHandler.cs:line 40
[17:24:38.674] No Support Module Loaded!

[latest.txt](https://github.com/user-attachments/files/15844472/latest.txt)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by AlphaLovesYou** [comment]
it would be much more helpful to provide a log file on the discord.
