### ISSUE TITLE
[Bug]: BTD6 similar to another one

### ISSUE THREAD

**Issue by nathanthrushyt** [LavaGang/MelonLoader#710]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [x] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[](url)
![2024-08-07](https://github.com/user-attachments/assets/fadcbe4e-0e4d-4ca4-b505-ad921a031ecf)

When I try starting the game I get the message below and the game crashes

[17:02:39.524] ------------------------------
[17:02:39.524] MelonLoader v0.6.1 Open-Beta
[17:02:39.526] OS: Windows 11
[17:02:39.526] Hash Code: 696B58144EEC73C72FA36A811CA73312EEE4EC28AD5E3527BDA1E14F388A
[17:02:39.526] ------------------------------
[17:02:39.526] Game Type: Il2cpp
[17:02:39.527] Game Arch: x64
[17:02:39.527] ------------------------------
[17:02:39.527] Core::BasePath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6
[17:02:39.527] Game::BasePath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6
[17:02:39.527] Game::DataPath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\BloonsTD6_Data
[17:02:39.528] Game::ApplicationPath = C:\Program Files (x86)\Steam\steamapps\common\BloonsTD6\BloonsTD6.exe
[17:02:39.528] Runtime Type: net6
[17:02:39.618] ------------------------------
[17:02:39.618] Game Name: BloonsTD6
[17:02:39.618] Game Developer: Ninja Kiwi
[17:02:39.620] Unity Version: 2021.3.16f1
[17:02:39.620] Game Version: unknown
![2024-08-07 (1)](https://github.com/user-attachments/assets/f9769e1e-d917-4c93-ac27-7f2c413b0d78)
![2024-08-07](https://github.com/user-attachments/assets/a8f9a192-b473-415c-857e-0c57ad5d454d)
[Latest.log](https://github.com/user-attachments/files/16533282/Latest.log)

[17:02:39.620] ------------------------------

[NewEntryPoint] Caught exception invoking Init
![2024-08-07 (1)](https://github.com/user-attachments/assets/e8edccf3-ea69-4f69-afd5-10d60954e42d)
![2024-08-07](https://github.com/user-attachments/assets/eb73efa0-76be-4dc1-b466-779e68d80595)
ialize! System.TypeInitializationException: The type initializer for 'HarmonyLib.Harmony' threw an exception.
---> System.IO.FileNotFoundException: Could not load file or assembly 'MonoMod.RuntimeDetour, Version=22.3.23.4, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'MonoMod.RuntimeDetour, Version=22.3.23.4, Culture=neutral, PublicKeyToken=null'
at HarmonyLib.Internal.RuntimeFixes.StackTraceFixes.Install()
at HarmonyLib.Harmony..cctor()
--- End of inner exception stack trace ---
at HarmonyLib.Harmony..ctor(String id)
at MelonLoader.Core.Initialize() in D:\a\MelonLoader\MelonLoader\MelonLoader\Core.cs:line 72
at MelonLoader.NativeHost.MelonLoaderInvoker.Initialize() in D:\a\MelonLoader\MelonLoader\MelonLoader.NativeHost\MelonLoaderInvoker.cs:line 10
at MelonLoader.NativeHost.NativeEntryPoint.Initialize() in D:\a\MelonLoader\MelonLoader\MelonLoader.NativeHost\NativeEntryPoint.cs:line 43
[Latest.log](https://github.com/user-attachments/files/16533286/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by HerpDerpinstine** [comment]
You are using the wrong MelonLoader version for BTD6.
Please downgrade to v0.6.1.
