### ISSUE TITLE
[Bug]: Il2CppAssemblyGenerator fails due to metadata, causing game to not launch

### ISSUE THREAD

**Issue by Niofluff** [LavaGang/MelonLoader#717]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[Latest.log](https://github.com/user-attachments/files/16624991/Latest.log)

Il2CppAssemblyGenerator seems to fail due to bad metadata, though i suspect this is a issue with the game itself (ensemble stars music)
i tried finding anyone reporting similar errors on other issies but couldnt find anything, sorry if this is an invalid issue

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by HerpDerpinstine** [comment]
Please retest this with the newest MelonLoader release of v0.6.5.

**Comment by Niofluff** [comment]
```[08:09:01.503] [Il2CppAssemblyGenerator] [Info] [Library] Initializing Metadata...
[08:09:01.562] [Il2CppAssemblyGenerator] [Fail] [Program]
[08:09:01.562] [Il2CppAssemblyGenerator]
[08:09:01.562] [Il2CppAssemblyGenerator] Cpp2IL.Core.Exceptions.LibCpp2ILInitializationException: Fatal Exception initializing LibCpp2IL!
[08:09:01.563] [Il2CppAssemblyGenerator]  ---> System.FormatException: Invalid or corrupt metadata (magic number check failed)
[08:09:01.563] [Il2CppAssemblyGenerator]    at LibCpp2IL.Metadata.Il2CppMetadata.ReadFrom(Byte[], UnityVersion) in C:\Users\Sam\RiderProjects\Cpp2IL\LibCpp2IL\Metadata\Il2CppMetadata.cs:line 65
[08:09:01.563] [Il2CppAssemblyGenerator]    at LibCpp2IL.LibCpp2IlMain.Initialize(Byte[], Byte[], UnityVersion) in C:\Users\Sam\RiderProjects\Cpp2IL\LibCpp2IL\LibCpp2IlMain.cs:line 155
[08:09:01.564] [Il2CppAssemblyGenerator]    at LibCpp2IL.LibCpp2IlMain.LoadFromFile(String, String, UnityVersion) in C:\Users\Sam\RiderProjects\Cpp2IL\LibCpp2IL\LibCpp2IlMain.cs:line 208
[08:09:01.564] [Il2CppAssemblyGenerator]    at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String, String, UnityVersion, Boolean ) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Cpp2IlApi.cs:line 66
[08:09:01.565] [Il2CppAssemblyGenerator]    --- End of inner exception stack trace ---
[08:09:01.565] [Il2CppAssemblyGenerator]    at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String, String, UnityVersion, Boolean ) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL.Core\Cpp2IlApi.cs:line 72
[08:09:01.565] [Il2CppAssemblyGenerator]    at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 587
[08:09:01.566] [Il2CppAssemblyGenerator]    at Cpp2IL.Program.Main(String[] args) in C:\Users\Sam\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 525
[08:09:01.566] [Il2CppAssemblyGenerator]
[08:09:01.566] [Il2CppAssemblyGenerator] Waiting for you to press enter - feel free to copy the error...```

**Comment by Niofluff** [comment]
[Latest.log](https://github.com/user-attachments/files/17261714/Latest.log)
here is the full log (with full reinstall both of melon launcher and game)

**Comment by slxdy** [comment]
I believe this game is either encrypted or heavily obfuscated. If not, then this should be reopened on Cpp2IL

**Comment by ekdl-max** [comment]
[Latest.log](https://github.com/user-attachments/files/18794436/Latest.log)

**Comment by Niofluff** [comment]
> I believe this game is either encrypted or heavily obfuscated. If not, then this should be reopened on Cpp2IL

Is there a way of running it with a decrypted version of the metadata?
