### ISSUE TITLE
[Bug]: bonelab crashing on startup

### ISSUE THREAD

**Issue by wildfrogy5** [LavaGang/MelonLoader#721]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

[22:26:15.086] ------------------------------
[22:26:15.086] MelonLoader v0.5.7 Open-Beta
[22:26:15.087] OS: Windows 11
[22:26:15.087] Hash Code: 49999848531024954985654485098975250521005157544948501005510199495356
[22:26:15.087] ------------------------------
[22:26:15.087] Game Type: Il2Cpp
[22:26:15.088] Game Arch: x64
[22:26:15.090] ------------------------------
[22:26:15.091] Core::BasePath = D:\SteamLibrary\steamapps\common\BONELAB
[22:26:15.091] Game::BasePath = D:\SteamLibrary\steamapps\common\BONELAB
[22:26:15.091] Game::DataPath = D:\SteamLibrary\steamapps\common\BONELAB\BONELAB_Steam_Windows64_Data
[22:26:15.092] Game::ApplicationPath = D:\SteamLibrary\steamapps\common\BONELAB\BONELAB_Steam_Windows64.exe

[22:26:17.588] ------------------------------
[22:26:17.588] Game Name: BONELAB
[22:26:17.589] Game Developer: Stress Level Zero
[22:26:17.591] Unity Version: 2021.3.5f1
[22:26:17.592] Game Version: 1.270.34555
[22:26:17.592] ------------------------------

[22:26:18.297] Preferences Loaded!
[22:26:18.335] [Il2CppUnityTls] Patching mono_unity_get_unitytls_interface...
[22:26:18.335] [Il2CppUnityTls] Patching il2cpp_unity_install_unitytls_interface...
[22:26:18.591] [Il2CppUnityTls] Calling Il2CppInstallUnityTlsInterface...

[22:26:18.677] Loading Plugins from 'D:\SteamLibrary\steamapps\common\BONELAB\Plugins'...
[22:26:18.677] ------------------------------
[22:26:18.683] Melon Assembly loaded: '.\Plugins\BoneLibUpdater.dll'
[22:26:18.683] SHA256 Hash: '325e9455cb6b586f3f9f58e68b5650bd650f7728d2dd04ee616f2fd3499d0e13'
[22:26:18.691] [ERROR] System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  at (wrapper managed-to-native) System.MonoCustomAttrs.GetCustomAttributesInternal(System.Reflection.ICustomAttributeProvider,System.Type,bool)
  at System.MonoCustomAttrs.GetCustomAttributesBase (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inheritedOnly) [0x00013] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at System.MonoCustomAttrs.GetCustomAttributes (System.Reflection.ICustomAttributeProvider obj, System.Type attributeType, System.Boolean inherit) [0x00037] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at System.Reflection.Assembly.GetCustomAttributes (System.Type attributeType, System.Boolean inherit) [0x00000] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at System.Attribute.GetCustomAttributes (System.Reflection.Assembly element, System.Boolean inherit) [0x00014] in <e1319b7195c343e79b385cd3aa43f5dc>:0 
  at MelonLoader.MelonUtils.PullAttributesFromAssembly[T] (System.Reflection.Assembly asm, System.Boolean inherit) [0x00000] in <6425afb6ac6a429aaf770255d2f7de57>:0 
  at MelonLoader.MelonUtils.PullAttributeFromAssembly[T] (System.Reflection.Assembly asm, System.Boolean inherit) [0x00000] in <6425afb6ac6a429aaf770255d2f7de57>:0 
  at MelonLoader.MelonAssembly.LoadMelons () [0x0008c] in <6425afb6ac6a429aaf770255d2f7de57>:0 
  at MelonLoader.MelonHandler.LoadMelonsFromDirectory[T] (System.String path) [0x000aa] in <6425afb6ac6a429aaf770255d2f7de57>:0 
  at MelonLoader.Core.Initialize () [0x0006e] in <6425afb6ac6a429aaf770255d2f7de57>:0 
this is the error code im getting

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by KibblesTheKitten** [comment]
You are using too new mods for patch 3.  You have to downgrade the mods or update to patch 5 and melon 0.6.4. and install .net 6

**Comment by wildfrogy5** [comment]
ohhhhhhh thanks ill try this and see if it fixes
also what is .net six?

**Comment by wildfrogy5** [comment]
uhhh kinda worked i installed a mod i wanted to use now its bricked again it gets to the start screen but when it loads eventually it errors
[22:43:00.589] ------------------------------
[22:43:00.611] MelonLoader v0.6.4 Open-Beta
[22:43:00.612] OS: Windows 11
[22:43:00.612] Hash Code: 57EE1B42E1FB9958A6BA7AB968E66098D05A9C82A5236075512B7E61BC7C2A65
[22:43:00.612] ------------------------------
[22:43:00.613] Game Type: Il2cpp
[22:43:00.613] Game Arch: x64
[22:43:00.613] ------------------------------
[22:43:00.613] Core::BasePath = D:\SteamLibrary\steamapps\common\BONELAB
[22:43:00.613] Game::BasePath = D:\SteamLibrary\steamapps\common\BONELAB
[22:43:00.613] Game::DataPath = D:\SteamLibrary\steamapps\common\BONELAB\BONELAB_Steam_Windows64_Data
[22:43:00.614] Game::ApplicationPath = D:\SteamLibrary\steamapps\common\BONELAB\BONELAB_Steam_Windows64.exe
[22:43:00.614] Runtime Type: net6
[22:43:00.696] ------------------------------
[22:43:00.697] Game Name: BONELAB
[22:43:00.697] Game Developer: Stress Level Zero
[22:43:00.698] Unity Version: 2021.3.5f1
[22:43:00.698] Game Version: 1.270.34555
[22:43:00.699] ------------------------------

[22:43:01.210] Preferences Loaded!

[22:43:01.385] Loading UserLibss from 'D:\SteamLibrary\steamapps\common\BONELAB\UserLibs'...

[22:43:01.392] Loading Plugins from 'D:\SteamLibrary\steamapps\common\BONELAB\Plugins'...
[22:43:01.392] ------------------------------
[22:43:01.396] Melon Assembly loaded: '.\Plugins\BoneLibUpdater.dll'
[22:43:01.396] SHA256 Hash: '325e9455cb6b586f3f9f58e68b5650bd650f7728d2dd04ee616f2fd3499d0e13'

[22:43:01.422] ------------------------------
[22:43:01.423] BoneLibUpdater v1.1.1
[22:43:01.423] by Gnonme
[22:43:01.423] Assembly: BoneLibUpdater.dll
[22:43:01.424] ------------------------------
[22:43:01.425] ------------------------------
[22:43:01.425] 1 Plugin loaded.
[22:43:01.440] [BoneLibUpdater] BoneLib is in ONLINE mode
[22:43:01.441] [BoneLibUpdater] BoneLib.dll found in Mods folder. Version: 3.1.0
[22:43:03.289] [BoneLibUpdater] BoneLib.dll updated successfully!
[22:43:05.155] [MelonStartScreen] Initializing...
[22:43:05.175] [MelonStartScreen] Using Start Screen Theme: "Default"
[22:43:05.996] Loading Il2CppAssemblyGenerator...
[22:43:06.007] [Il2CppAssemblyGenerator] Contacting RemoteAPI...
[22:43:06.170] [Il2CppAssemblyGenerator] Game Not Found on RemoteAPI Host (https://api.melonloader.com/api/v1/game/bonelab)
[22:43:06.171] [Il2CppAssemblyGenerator] RemoteAPI.DumperVersion = null
[22:43:06.172] [Il2CppAssemblyGenerator] RemoteAPI.ObfuscationRegex = null
[22:43:06.172] [Il2CppAssemblyGenerator] RemoteAPI.MappingURL = null
[22:43:06.172] [Il2CppAssemblyGenerator] RemoteAPI.MappingFileSHA512 = null
[22:43:06.178] [Il2CppAssemblyGenerator] Using Dumper Version: 2022.1.0-pre-release.15
[22:43:06.178] [Il2CppAssemblyGenerator] Using Il2CppInterop Version = 1.4.6-ci.433+45e22c2cb80a9586114a1815d77cc20104fd896c
[22:43:06.178] [Il2CppAssemblyGenerator] Using Unity Dependencies Version = 2021.3.5
[22:43:06.179] [Il2CppAssemblyGenerator] Using Deobfuscation Regex = null
[22:43:06.179] [Il2CppAssemblyGenerator] Cpp2IL is up to date.
[22:43:06.180] [Il2CppAssemblyGenerator] UnityDependencies is up to date.
[22:43:06.180] [Il2CppAssemblyGenerator] Checking GameAssembly...
[22:43:06.304] [Il2CppAssemblyGenerator] Assembly is up to date. No Generation Needed.

[22:43:06.323] Loading Mods from 'D:\SteamLibrary\steamapps\common\BONELAB\Mods'...
[22:43:06.325] ------------------------------
[22:43:06.345] Melon Assembly loaded: '.\Mods\AudioImportLib.dll'
[22:43:06.345] SHA256 Hash: '92484fabe1c1f12590112ffcabdebe5da6fc23d38a0dfb77dd344589716c50df'
[22:43:06.373] Melon Assembly loaded: '.\Mods\BoneLib.dll'
[22:43:06.374] SHA256 Hash: '302235c57295a1aed3ddd6079d01f535f2de06fc0e161f90e6d1c137cb23774e'
[22:43:06.378] Melon Assembly loaded: '.\Mods\JeviLib.dll'
[22:43:06.378] SHA256 Hash: '92953ed63e43a5e277dae81699029eccaac5529721457c374910a6cd6e21a117'
[22:43:06.382] Melon Assembly loaded: '.\Mods\MonoDirector.dll'
[22:43:06.382] SHA256 Hash: '06d794606d064235170fb12b361f31d69d21480f45c330cc2a83ab940c0bcf56'

[22:43:06.602] Some Melons are missing dependencies, which you may have to install.
If these are optional dependencies, mark them as optional using the MelonOptionalDependencies attribute.
This warning will turn into an error and Melons with missing dependencies will not be loaded in the next version of MelonLoader.
- 'JeviLib' is missing the following dependencies:
    - 'UniTask' v0.0.0.0
    - 'SLZ.Marrow.SDK' v0.0.0.0
    - 'SLZ.Marrow' v0.0.0.0
    - 'UnhollowerBaseLib' v0.4.18.0
- 'MonoDirector' is missing the following dependencies:
    - 'SLZ.Marrow' v0.0.0.0
    - 'SLZ.Marrow.SDK' v0.0.0.0
    - 'UnhollowerBaseLib' v0.4.18.0
[22:43:06.610] ------------------------------
[22:43:06.610] BoneLib v3.1.0
[22:43:06.610] by The BONELAB Modding Community
[22:43:06.610] Assembly: BoneLib.dll
[22:43:06.611] ------------------------------
[22:43:06.617] Failed to register Mod 'D:\SteamLibrary\steamapps\common\BONELAB\Mods\JeviLib.dll': Melon failed to initialize!
[22:43:06.618] System.MissingMethodException: Method not found: 'Void BoneLib.Hooking.add_OnLevelInitialized(System.Action`1<BoneLib.LevelInfo>)'.
   at Jevil.JeviLib.OnEarlyInitializeMelon()
   at MelonLoader.MelonBase.Register() in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\MelonBase.cs:line 397
[22:43:06.623] ------------------------------
[22:43:06.623] MonoDirector v0.0.1
[22:43:06.623] by Not Enough Photons
[22:43:06.624] Assembly: MonoDirector.dll
[22:43:06.624] ------------------------------
[22:43:06.629] ------------------------------
[22:43:06.630] AudioImportLib v1.0.0
[22:43:06.630] by trev & zCubed
[22:43:06.632] Assembly: AudioImportLib.dll
[22:43:06.632] ------------------------------
[22:43:06.633] ------------------------------
[22:43:06.633] 3 Mods loaded.

[22:43:07.033] Class::Init signatures have been exhausted, using a substitute!
[22:43:07.108] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[22:43:07.134] Registered mono type MelonLoader.Support.MonoEnumeratorWrapper in il2cpp domain
[22:43:07.136] Registered mono type MelonLoader.Support.SM_Component in il2cpp domain
[22:43:07.143] Support Module Loaded: D:\SteamLibrary\steamapps\common\BONELAB\MelonLoader\Dependencies\SupportModules\Il2Cpp.dll
[22:43:07.163] Method Void DrawHeader(BoneLib.BoneMenu.Page) on type BoneLib.BoneMenu.UI.GUIMenu has unsupported parameter BoneLib.BoneMenu.Page page of type BoneLib.BoneMenu.Page
[22:43:07.164] Method Void DrawBackground(BoneLib.BoneMenu.Page) on type BoneLib.BoneMenu.UI.GUIMenu has unsupported parameter BoneLib.BoneMenu.Page page of type BoneLib.BoneMenu.Page
[22:43:07.164] Method Void DrawFooter(BoneLib.BoneMenu.Page) on type BoneLib.BoneMenu.UI.GUIMenu has unsupported parameter BoneLib.BoneMenu.Page page of type BoneLib.BoneMenu.Page
[22:43:07.168] Method Void DrawElements(BoneLib.BoneMenu.Page) on type BoneLib.BoneMenu.UI.GUIMenu has unsupported parameter BoneLib.BoneMenu.Page page of type BoneLib.BoneMenu.Page
[22:43:07.184] Failed to load all types in assembly JeviLib, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null due to: Unable to load one or more of the requested types.
Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'SLZ.Marrow.SDK, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'SLZ.Marrow.SDK, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at MelonLoader.MelonUtils.GetValidTypes(Assembly asm, LemonFunc`2 predicate) in D:\a\MelonLoader\MelonLoader\MelonLoader\MelonUtils.cs:line 258
System.IO.FileNotFoundException: Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'SLZ.Marrow.SDK, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'SLZ.Marrow.SDK, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
[22:43:07.185] Registered mono type Jevil.NeverCollect in il2cpp domain
[22:43:07.187] Failed to load all types in assembly MonoDirector, Version=0.0.1.0, Culture=neutral, PublicKeyToken=null due to: Unable to load one or more of the requested types.
Could not load type 'AnimationStates' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load type 'AnimationStates' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at MelonLoader.MelonUtils.GetValidTypes(Assembly asm, LemonFunc`2 predicate) in D:\a\MelonLoader\MelonLoader\MelonLoader\MelonUtils.cs:line 258
System.TypeLoadException: Could not load type 'AnimationStates' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by wildfrogy5** [comment]
didint mean to close this

**Comment by galacticatron** [comment]
do you have mcafee installed

**Comment by psyellas** [comment]
this isnt an antivirus issue, the person just can't read instructions
they got told upgrade to **patch 5** and update melonloader to 0.6.4, and they only updated melonloader

**Comment by wildfrogy5** [comment]
Ah i see I had the beta on my apologies

**Comment by AltruisticRambler** [comment]
I just solved this issue partly on my install as well! Current patch, current melonloader, it was still failing with various .net errors. I tried repairing my .net V6 install and it still had the error -- BUT uninstalling & reinstalling .net V6 TOTALLY WORKED! =D 

Unfortunately, the game _almost_ launches now, but I'm seeing the following just after all my mods run= 

```
[22:14:20.558] MelonLoader v0.6.4 Open-Beta
[22:14:20.558] OS: Windows 10
[22:14:20.559] Hash Code: 57EE1B42E1FB9958A6BA7AB968E66098D05A9C82A5236075512B7E61BC7C2A65
[22:14:20.559] ------------------------------
[22:14:20.559] Game Type: Il2cpp
[22:14:20.559] Game Arch: x64
[22:14:20.559] ------------------------------
[22:14:20.560] Core::BasePath = T:\SteamLibrary\steamapps\common\BONELAB
[22:14:20.560] Game::BasePath = T:\SteamLibrary\steamapps\common\BONELAB
[22:14:20.560] Game::DataPath = T:\SteamLibrary\steamapps\common\BONELAB\BONELAB_Steam_Windows64_Data
[22:14:20.561] Game::ApplicationPath = T:\SteamLibrary\steamapps\common\BONELAB\BONELAB_Steam_Windows64.exe
[22:14:20.561] Runtime Type: net6
[22:14:20.632] ------------------------------
[22:14:20.632] Game Name: BONELAB
[22:14:20.633] Game Developer: Stress Level Zero
[22:14:20.634] Unity Version: 2021.3.16f1
[22:14:20.634] Game Version: 1.642.56657
[22:14:20.634] ------------------------------

[22:14:21.198] Preferences Loaded!

[22:14:21.517] Loading UserLibss from 'T:\SteamLibrary\steamapps\common\BONELAB\UserLibs'...

[22:14:21.524] Loading Plugins from 'T:\SteamLibrary\steamapps\common\BONELAB\Plugins'...
[22:14:21.524] ------------------------------
[22:14:21.529] Melon Assembly loaded: '.\Plugins\BoneLibUpdater.dll'
[22:14:21.530] SHA256 Hash: '325e9455cb6b586f3f9f58e68b5650bd650f7728d2dd04ee616f2fd3499d0e13'
[22:14:21.532] Melon Assembly loaded: '.\Plugins\LabFusionUpdater.dll'
[22:14:21.532] SHA256 Hash: '4b09dc8d9b94906c398289a484aad624f2fac711c191d51df7cc49060886f8a8'

[22:14:21.561] ------------------------------
[22:14:21.562] BoneLibUpdater v1.1.1
[22:14:21.562] by Gnonme
[22:14:21.562] Assembly: BoneLibUpdater.dll
[22:14:21.562] ------------------------------
[22:14:21.567] ------------------------------
[22:14:21.567] LabFusion Updater v1.0.0
[22:14:21.567] by Lakatrazz
[22:14:21.567] Assembly: LabFusionUpdater.dll
[22:14:21.568] ------------------------------
[22:14:21.568] ------------------------------
[22:14:21.568] 2 Plugins loaded.
[22:14:21.586] [BoneLibUpdater] BoneLib is in ONLINE mode
[22:14:21.588] [BoneLibUpdater] BoneLib.dll found in Mods folder. Version: 3.1.0
Latest version of BoneLib is 3.1.1
Downloading latest version...
[22:14:23.947] [BoneLibUpdater] BoneLib.dll updated successfully!
[22:14:23.948] [LabFusion_Updater] Fusion Auto-Updater is ONLINE.
[22:14:23.949] [LabFusion_Updater] LabFusion.dll found in Mods folder. Version: 1.7.0
Latest version of LabFusion is 1.7.0.
[22:14:25.135] [LabFusion_Updater] LabFusion.dll is already up to date.
xrNegotiateLoaderRuntimeInterface bRunningInAppContainer: 0
[NewEntryPoint] PreStarting.
[22:14:26.097] [MelonStartScreen] Initializing...
[22:14:26.117] [MelonStartScreen] Using Start Screen Theme: "Default"
[22:14:27.173] Loading Il2CppAssemblyGenerator...
[22:14:27.184] [Il2CppAssemblyGenerator] Contacting RemoteAPI...
[22:14:27.459] [Il2CppAssemblyGenerator] Game Not Found on RemoteAPI Host (https://api.melonloader.com/api/v1/game/bonelab)
[22:14:27.459] [Il2CppAssemblyGenerator] RemoteAPI.DumperVersion = null
[22:14:27.460] [Il2CppAssemblyGenerator] RemoteAPI.ObfuscationRegex = null
[22:14:27.461] [Il2CppAssemblyGenerator] RemoteAPI.MappingURL = null
[22:14:27.461] [Il2CppAssemblyGenerator] RemoteAPI.MappingFileSHA512 = null
[22:14:27.468] [Il2CppAssemblyGenerator] Using Dumper Version: 2022.1.0-pre-release.15
[22:14:27.468] [Il2CppAssemblyGenerator] Using Il2CppInterop Version = 1.4.6-ci.433+45e22c2cb80a9586114a1815d77cc20104fd896c
[22:14:27.469] [Il2CppAssemblyGenerator] Using Unity Dependencies Version = 2021.3.16
[22:14:27.469] [Il2CppAssemblyGenerator] Using Deobfuscation Regex = null
[22:14:27.470] [Il2CppAssemblyGenerator] Cpp2IL is up to date.
[22:14:27.470] [Il2CppAssemblyGenerator] UnityDependencies is up to date.
[22:14:27.470] [Il2CppAssemblyGenerator] Checking GameAssembly...
[22:14:27.629] [Il2CppAssemblyGenerator] Assembly is up to date. No Generation Needed.
[NewEntryPoint] Starting.

[22:14:27.640] Loading Mods from 'T:\SteamLibrary\steamapps\common\BONELAB\Mods'...
[22:14:27.642] ------------------------------
[22:14:27.684] Melon Assembly loaded: '.\Mods\BoneLib.dll'
[22:14:27.684] SHA256 Hash: '302235c57295a1aed3ddd6079d01f535f2de06fc0e161f90e6d1c137cb23774e'
[22:14:27.722] Melon Assembly loaded: '.\Mods\LabFusion.dll'
[22:14:27.722] SHA256 Hash: '3dbf8b1a3db0a78dd8d114bba78dd45278ef4619376404e6bf83cf6624ccbe75'
[22:14:27.736] Melon Assembly loaded: '.\Mods\SpiderLab.dll'
[22:14:27.736] SHA256 Hash: 'c88627d997673500193ea5600159ad5def8236c2ea4386d24f9d3252237ff386'
[22:14:27.746] Melon Assembly loaded: '.\Mods\SpiderlabFusionSync.dll'
[22:14:27.746] SHA256 Hash: 'b0f31cf328e683cc01f1262b8510519c0c953042db17821d841f375e909dd148'

[22:14:28.062] Some Melons are missing dependencies, which you may have to install.
If these are optional dependencies, mark them as optional using the MelonOptionalDependencies attribute.
This warning will turn into an error and Melons with missing dependencies will not be loaded in the next version of MelonLoader.
- 'SpiderLab' is missing the following dependencies:
    - 'SLZ.Marrow' v0.0.0.0
    - 'UnhollowerBaseLib' v0.4.18.0
- 'SpiderlabFusionSync' is missing the following dependencies:
    - 'UnhollowerBaseLib' v0.4.18.0
[22:14:28.080] ------------------------------
[22:14:28.080] BoneLib v3.1.0
[22:14:28.080] by The BONELAB Modding Community
[22:14:28.081] Assembly: BoneLib.dll
[22:14:28.082] ------------------------------
[22:14:28.102] [LabFusion] Data is at C:/Users/xttweaponttx/AppData/LocalLow/Stress Level Zero/BONELAB/Fusion/.
[22:14:28.102] [LabFusion] steam_api64.dll already exists, skipping extraction.
[22:14:28.106] [LabFusion] Successfully loaded steam_api64.dll into the application!
[22:14:28.109] ------------------------------
[22:14:28.109] LabFusion v1.7.0
[22:14:28.109] by Lakatrazz
[22:14:28.110] Assembly: LabFusion.dll
[22:14:28.110] ------------------------------
[22:14:28.122] ------------------------------
[22:14:28.122] SpiderLab v1.0.2
[22:14:28.122] by Parzival
[22:14:28.122] Assembly: SpiderLab.dll
[22:14:28.123] ------------------------------
[22:14:28.133] ------------------------------
[22:14:28.133] SpiderlabFusionSync v1.1.0
[22:14:28.133] by notnotnotswipez
[22:14:28.134] Assembly: SpiderlabFusionSync.dll
[22:14:28.134] ------------------------------
[22:14:28.135] ------------------------------
[22:14:28.135] 4 Mods loaded.

[22:14:28.585] Class::Init signatures have been exhausted, using a substitute!
[22:14:28.671] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[22:14:28.698] Registered mono type MelonLoader.Support.MonoEnumeratorWrapper in il2cpp domain
[22:14:28.700] Registered mono type MelonLoader.Support.SM_Component in il2cpp domain
[22:14:28.707] Support Module Loaded: T:\SteamLibrary\steamapps\common\BONELAB\MelonLoader\Dependencies\SupportModules\Il2Cpp.dll
[22:14:28.726] Method Void DrawHeader(BoneLib.BoneMenu.Page) on type BoneLib.BoneMenu.UI.GUIMenu has unsupported parameter BoneLib.BoneMenu.Page page of type BoneLib.BoneMenu.Page
[22:14:28.726] Method Void DrawBackground(BoneLib.BoneMenu.Page) on type BoneLib.BoneMenu.UI.GUIMenu has unsupported parameter BoneLib.BoneMenu.Page page of type BoneLib.BoneMenu.Page
[22:14:28.727] Method Void DrawFooter(BoneLib.BoneMenu.Page) on type BoneLib.BoneMenu.UI.GUIMenu has unsupported parameter BoneLib.BoneMenu.Page page of type BoneLib.BoneMenu.Page
[22:14:28.727] Method Void DrawElements(BoneLib.BoneMenu.Page) on type BoneLib.BoneMenu.UI.GUIMenu has unsupported parameter BoneLib.BoneMenu.Page page of type BoneLib.BoneMenu.Page
[22:14:28.765] Registered mono type LabFusion.UI.FusionUIMachine in il2cpp domain
[22:14:28.768] Registered mono type LabFusion.UI.CupBoard in il2cpp domain
[22:14:28.770] Registered mono type LabFusion.UI.FusionPanelView in il2cpp domain
[22:14:28.772] Registered mono type LabFusion.UI.CupBoardPanelView in il2cpp domain
[22:14:28.773] Registered mono type LabFusion.UI.FusionUITrigger in il2cpp domain
[22:14:28.774] Registered mono type LabFusion.UI.InfoBox in il2cpp domain
[22:14:28.775] Registered mono type LabFusion.UI.InfoBoxPanelView in il2cpp domain
[22:14:28.777] Registered mono type LabFusion.SDK.Points.PointShop in il2cpp domain
[22:14:28.780] Registered mono type LabFusion.SDK.Points.PointShopPanelView in il2cpp domain
[22:14:28.782] Registered mono type LabFusion.MonoBehaviours.CollisionSyncer in il2cpp domain
[22:14:28.783] Registered mono type LabFusion.MonoBehaviours.DestroyOnDisconnect in il2cpp domain
[22:14:28.784] Registered mono type LabFusion.MonoBehaviours.DestroySensor in il2cpp domain
[22:14:28.785] Registered mono type LabFusion.MonoBehaviours.MirrorIdentifier in il2cpp domain
[22:14:28.786] Registered mono type LabFusion.MonoBehaviours.NotifyOnEnable in il2cpp domain
[22:14:28.787] Registered mono type LabFusion.MonoBehaviours.TimedDespawner in il2cpp domain
[22:14:28.791] Registered mono type LabFusion.Marrow.Integration.AvatarCosmeticPoint in il2cpp domain
[22:14:28.794] Registered mono type LabFusion.Marrow.Integration.CosmeticRoot in il2cpp domain
[22:14:28.795] Registered mono type LabFusion.Marrow.Integration.CelebrationEvents in il2cpp domain
[22:14:28.797] Registered mono type LabFusion.Marrow.Integration.OwnershipEvents in il2cpp domain
[22:14:28.798] Registered mono type LabFusion.Marrow.Integration.ServerEvents in il2cpp domain
[22:14:28.799] Registered mono type LabFusion.Marrow.Integration.BitTransactor in il2cpp domain
[22:14:28.800] Registered mono type LabFusion.Marrow.Integration.GamemodeEvents in il2cpp domain
[22:14:28.801] Registered mono type LabFusion.Marrow.Integration.GamemodeMarker in il2cpp domain
[22:14:28.803] Registered mono type LabFusion.Marrow.Integration.RPCEvent in il2cpp domain
[22:14:28.804] Registered mono type LabFusion.Marrow.Proxies.AchievementBoard in il2cpp domain
[22:14:28.805] Registered mono type LabFusion.Marrow.Proxies.BitMart in il2cpp domain
[22:14:28.805] Registered mono type LabFusion.Marrow.Proxies.InfoBoard in il2cpp domain
[NewEntryPoint] Caught exception invoking Start! System.TypeLoadException: Could not load type 'SLZ.Rig.RigManager' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Signature.GetSignature(Void* pCorSig, Int32 cCorSig, RuntimeFieldHandleInternal fieldHandle, IRuntimeMethodInfo methodHandle, RuntimeType declaringType)
   at System.Reflection.RtFieldInfo.InitializeFieldType()
   at Il2CppInterop.Runtime.Injection.ClassInjector.IsFieldEligible(FieldInfo field) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/ClassInjector.cs:line 543
   at System.Linq.Enumerable.WhereArrayIterator`1.ToArray()
   at Il2CppInterop.Runtime.Injection.ClassInjector.RegisterTypeInIl2Cpp(Type type, RegisterTypeOptions options) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Injection/ClassInjector.cs:line 248
   at MelonLoader.Support.InteropInterface.RegisterTypeInIl2CppDomain(Type type, Boolean logSuccess) in D:\a\MelonLoader\MelonLoader\Dependencies\SupportModules\Il2Cpp\InteropInterface.cs:line 30
   at MelonLoader.InteropSupport.RegisterTypeInIl2CppDomain(Type type, Boolean logSuccess) in D:\a\MelonLoader\MelonLoader\MelonLoader\Utils\InteropSupport.cs:line 98
   at MelonLoader.RegisterTypeInIl2Cpp.RegisterAssembly(Assembly asm) in D:\a\MelonLoader\MelonLoader\MelonLoader\Attributes\RegisterTypeInIl2Cpp.cs:line 40
   at MelonLoader.RegisterTypeInIl2Cpp.SetReady() in D:\a\MelonLoader\MelonLoader\MelonLoader\Attributes\RegisterTypeInIl2Cpp.cs:line 51
   at MelonLoader.Core.Start() in D:\a\MelonLoader\MelonLoader\MelonLoader\Core.cs:line 135
   at MelonLoader.NativeHost.NativeEntryPoint.Start() in D:\a\MelonLoader\MelonLoader\MelonLoader.NativeHost\NativeEntryPoint.cs:line 75
```

Hope you folks are keeping your sanity through the wave of crash reports you're probably wading through with these patches rolling out! Cheers for the kickass mod loader <3

edit: accidentally left some of my comments within the code block loloops

**Comment by AltruisticRambler** [comment]
Update -- I downgraded through the last few versions (6.3, .2, and .1) and I'm getting the same error on all those versions too! 

```
Could not load type 'SLZ.Rig.RigManager'............
etc, see above
```

for good measure, I also tried out another .net uninstall & reinstall with all the mods & loader in place. Still nothin 🤔
