### ISSUE TITLE
[Bug]: open xr

### ISSUE THREAD

**Issue by wildfrogy5** [LavaGang/MelonLoader#722]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [ ] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [X] Was able to see the Start Screen.

### Describe the issue.

got told something about openxr failing to verify my headset is this a bug because i arent activly on my headset while testing
[22:54:47.809] ------------------------------
[22:54:47.830] MelonLoader v0.6.4 Open-Beta
[22:54:47.831] OS: Windows 11
[22:54:47.832] Hash Code: 57EE1B42E1FB9958A6BA7AB968E66098D05A9C82A5236075512B7E61BC7C2A65
[22:54:47.832] ------------------------------
[22:54:47.832] Game Type: Il2cpp
[22:54:47.832] Game Arch: x64
[22:54:47.832] ------------------------------
[22:54:47.833] Core::BasePath = D:\SteamLibrary\steamapps\common\BONELAB
[22:54:47.833] Game::BasePath = D:\SteamLibrary\steamapps\common\BONELAB
[22:54:47.833] Game::DataPath = D:\SteamLibrary\steamapps\common\BONELAB\BONELAB_Steam_Windows64_Data
[22:54:47.833] Game::ApplicationPath = D:\SteamLibrary\steamapps\common\BONELAB\BONELAB_Steam_Windows64.exe
[22:54:47.833] Runtime Type: net6
[22:54:47.904] ------------------------------
[22:54:47.904] Game Name: BONELAB
[22:54:47.904] Game Developer: Stress Level Zero
[22:54:47.905] Unity Version: 2021.3.5f1
[22:54:47.906] Game Version: 1.270.34555
[22:54:47.906] ------------------------------

[22:54:48.442] Preferences Loaded!

[22:54:48.632] Loading UserLibss from 'D:\SteamLibrary\steamapps\common\BONELAB\UserLibs'...

[22:54:48.640] Loading Plugins from 'D:\SteamLibrary\steamapps\common\BONELAB\Plugins'...
[22:54:48.641] ------------------------------
[22:54:48.645] Melon Assembly loaded: '.\Plugins\BoneLibUpdater.dll'
[22:54:48.645] SHA256 Hash: '325e9455cb6b586f3f9f58e68b5650bd650f7728d2dd04ee616f2fd3499d0e13'

[22:54:48.673] ------------------------------
[22:54:48.673] BoneLibUpdater v1.1.1
[22:54:48.673] by Gnonme
[22:54:48.673] Assembly: BoneLibUpdater.dll
[22:54:48.673] ------------------------------
[22:54:48.674] ------------------------------
[22:54:48.674] 1 Plugin loaded.
[22:54:48.690] [BoneLibUpdater] BoneLib is in ONLINE mode
[22:54:48.691] [BoneLibUpdater] BoneLib.dll found in Mods folder. Version: 3.1.0
[22:54:51.275] [BoneLibUpdater] BoneLib.dll updated successfully!
[22:54:52.185] [MelonStartScreen] Initializing...
[22:54:52.207] [MelonStartScreen] Using Start Screen Theme: "Default"
[22:54:53.047] Loading Il2CppAssemblyGenerator...
[22:54:53.059] [Il2CppAssemblyGenerator] Contacting RemoteAPI...
[22:54:53.287] [Il2CppAssemblyGenerator] Game Not Found on RemoteAPI Host (https://api.melonloader.com/api/v1/game/bonelab)
[22:54:53.289] [Il2CppAssemblyGenerator] RemoteAPI.DumperVersion = null
[22:54:53.290] [Il2CppAssemblyGenerator] RemoteAPI.ObfuscationRegex = null
[22:54:53.290] [Il2CppAssemblyGenerator] RemoteAPI.MappingURL = null
[22:54:53.290] [Il2CppAssemblyGenerator] RemoteAPI.MappingFileSHA512 = null
[22:54:53.295] [Il2CppAssemblyGenerator] Using Dumper Version: 2022.1.0-pre-release.15
[22:54:53.296] [Il2CppAssemblyGenerator] Using Il2CppInterop Version = 1.4.6-ci.433+45e22c2cb80a9586114a1815d77cc20104fd896c
[22:54:53.296] [Il2CppAssemblyGenerator] Using Unity Dependencies Version = 2021.3.5
[22:54:53.296] [Il2CppAssemblyGenerator] Using Deobfuscation Regex = null
[22:54:53.297] [Il2CppAssemblyGenerator] Cpp2IL is up to date.
[22:54:53.297] [Il2CppAssemblyGenerator] UnityDependencies is up to date.
[22:54:53.298] [Il2CppAssemblyGenerator] Checking GameAssembly...
[22:54:53.419] [Il2CppAssemblyGenerator] Assembly is up to date. No Generation Needed.

[22:54:53.445] Loading Mods from 'D:\SteamLibrary\steamapps\common\BONELAB\Mods'...
[22:54:53.447] ------------------------------
[22:54:53.911] Melon Assembly loaded: '.\Mods\AnyMagazine.dll'
[22:54:53.912] SHA256 Hash: '5a916011504ac8c99317cc6ed21e083b9f303b0f1879deba2006e5fff0efd3b0'
[22:54:53.919] Melon Assembly loaded: '.\Mods\AudioImportLib.dll'
[22:54:53.919] SHA256 Hash: '92484fabe1c1f12590112ffcabdebe5da6fc23d38a0dfb77dd344589716c50df'
[22:54:53.929] Melon Assembly loaded: '.\Mods\BoneLib.dll'
[22:54:53.929] SHA256 Hash: '302235c57295a1aed3ddd6079d01f535f2de06fc0e161f90e6d1c137cb23774e'
[22:54:53.933] Melon Assembly loaded: '.\Mods\JeviLib.dll'
[22:54:53.933] SHA256 Hash: '92953ed63e43a5e277dae81699029eccaac5529721457c374910a6cd6e21a117'

[22:54:54.115] Some Melons are missing dependencies, which you may have to install.
If these are optional dependencies, mark them as optional using the MelonOptionalDependencies attribute.
This warning will turn into an error and Melons with missing dependencies will not be loaded in the next version of MelonLoader.
- 'JeviLib' is missing the following dependencies:
    - 'UniTask' v0.0.0.0
    - 'SLZ.Marrow.SDK' v0.0.0.0
    - 'SLZ.Marrow' v0.0.0.0
    - 'UnhollowerBaseLib' v0.4.18.0
[22:54:54.127] ------------------------------
[22:54:54.127] BoneLib v3.1.0
[22:54:54.127] by The BONELAB Modding Community
[22:54:54.128] Assembly: BoneLib.dll
[22:54:54.128] ------------------------------
[22:54:54.134] Failed to register Mod 'D:\SteamLibrary\steamapps\common\BONELAB\Mods\JeviLib.dll': Melon failed to initialize!
[22:54:54.135] System.MissingMethodException: Method not found: 'Void BoneLib.Hooking.add_OnLevelInitialized(System.Action`1<BoneLib.LevelInfo>)'.
   at Jevil.JeviLib.OnEarlyInitializeMelon()
   at MelonLoader.MelonBase.Register() in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\MelonBase.cs:line 397
[22:54:54.141] ------------------------------
[22:54:54.141] AnyMagazine v1.0.1
[22:54:54.141] by Rexmeck
[22:54:54.142] Assembly: AnyMagazine.dll
[22:54:54.142] ------------------------------
[22:54:54.148] ------------------------------
[22:54:54.148] AudioImportLib v1.0.0
[22:54:54.148] by trev & zCubed
[22:54:54.149] Assembly: AudioImportLib.dll
[22:54:54.149] ------------------------------
[22:54:54.150] ------------------------------
[22:54:54.150] 3 Mods loaded.

[22:54:54.556] Class::Init signatures have been exhausted, using a substitute!
[22:54:54.633] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[22:54:54.658] Registered mono type MelonLoader.Support.MonoEnumeratorWrapper in il2cpp domain
[22:54:54.660] Registered mono type MelonLoader.Support.SM_Component in il2cpp domain
[22:54:54.666] Support Module Loaded: D:\SteamLibrary\steamapps\common\BONELAB\MelonLoader\Dependencies\SupportModules\Il2Cpp.dll
[22:54:54.686] Method Void DrawHeader(BoneLib.BoneMenu.Page) on type BoneLib.BoneMenu.UI.GUIMenu has unsupported parameter BoneLib.BoneMenu.Page page of type BoneLib.BoneMenu.Page
[22:54:54.687] Method Void DrawBackground(BoneLib.BoneMenu.Page) on type BoneLib.BoneMenu.UI.GUIMenu has unsupported parameter BoneLib.BoneMenu.Page page of type BoneLib.BoneMenu.Page
[22:54:54.687] Method Void DrawFooter(BoneLib.BoneMenu.Page) on type BoneLib.BoneMenu.UI.GUIMenu has unsupported parameter BoneLib.BoneMenu.Page page of type BoneLib.BoneMenu.Page
[22:54:54.688] Method Void DrawElements(BoneLib.BoneMenu.Page) on type BoneLib.BoneMenu.UI.GUIMenu has unsupported parameter BoneLib.BoneMenu.Page page of type BoneLib.BoneMenu.Page
[22:54:54.702] Failed to load all types in assembly JeviLib, Version=2.2.1.0, Culture=neutral, PublicKeyToken=null due to: Unable to load one or more of the requested types.
Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'SLZ.Marrow.SDK, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
Could not load file or assembly 'SLZ.Marrow.SDK, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at MelonLoader.MelonUtils.GetValidTypes(Assembly asm, LemonFunc`2 predicate) in D:\a\MelonLoader\MelonLoader\MelonLoader\MelonUtils.cs:line 258
System.IO.FileNotFoundException: Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
System.IO.FileNotFoundException: Could not load file or assembly 'SLZ.Marrow.SDK, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'SLZ.Marrow.SDK, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
[22:54:54.704] Registered mono type Jevil.NeverCollect in il2cpp domain
[22:54:54.705] [AnyMagazine] System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.AmmoPlug' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at System.Reflection.CustomAttribute._CreateCaObject(RuntimeModule pModule, RuntimeType type, IRuntimeMethodInfo pCtor, Byte** ppBlob, Byte* pEndBlob, Int32* pcNamedArgs)
   at System.Reflection.CustomAttribute.AddCustomAttributes(ListBuilder`1& attributes, RuntimeModule decoratedModule, Int32 decoratedMetadataToken, RuntimeType attributeFilterType, Boolean mustBeInheritable, ListBuilder`1 derivedAttributes)
   at System.Reflection.CustomAttribute.GetCustomAttributes(RuntimeType type, RuntimeType caType, Boolean inherit)
   at System.RuntimeType.GetCustomAttributes(Boolean inherit)
   at HarmonyLib.HarmonyMethodExtensions.GetFromType(Type type)
   at HarmonyLib.PatchClassProcessor..ctor(Harmony instance, Type type, Boolean allowUnannotatedType)
   at HarmonyLib.PatchClassProcessor..ctor(Harmony instance, Type type)
   at HarmonyLib.Harmony.CreateClassProcessor(Type type)
   at HarmonyLib.Harmony.<PatchAll>b__11_0(Type type)
   at HarmonyLib.CollectionExtensions.Do[T](IEnumerable`1 sequence, Action`1 action)
   at HarmonyLib.Harmony.PatchAll(Assembly assembly)
   at MelonLoader.MelonMod.HarmonyInit() in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\MelonMod.cs:line 40
   at MelonLoader.MelonEvent.<>c.<Invoke>b__1_0(LemonAction x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 174
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[22:54:54.731] [BoneLib] System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.Warehouse.AssetWarehouse' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at BoneLib.Hooking.InitHooks()
   at BoneLib.Main.OnInitializeMelon()
   at MelonLoader.MelonBase.LoaderInitialized() in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\MelonBase.cs:line 440
[22:54:54.734] [AnyMagazine] BoneMenu Not Detected!
[22:54:55.125] [BoneLib] System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.OpenControllerRig' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at BoneLib.Main.OnUpdate()
   at MelonLoader.MelonEvent.<>c.<Invoke>b__1_0(LemonAction x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 174
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[22:54:55.126] [JeviLib] System.IO.FileNotFoundException: Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Jevil.JeviLib.OnUpdate()
   at MelonLoader.MelonEvent.<>c.<Invoke>b__1_0(LemonAction x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 174
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[22:54:55.398] [JeviLib] System.TypeLoadException: Could not load type 'SLZ.Rig.RigManager' from assembly 'Assembly-CSharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Jevil.JeviLib.OnSceneWasInitialized(Int32 buildIndex, String sceneName)
   at MelonLoader.MelonEvent`2.<>c__DisplayClass1_0.<Invoke>b__0(LemonAction`2 x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 192
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[22:54:55.399] [BoneLib] System.TypeLoadException: Could not load type 'Il2CppSLZ.Marrow.OpenControllerRig' from assembly 'Il2CppSLZ.Marrow, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at BoneLib.Main.OnUpdate()
   at MelonLoader.MelonEvent.<>c.<Invoke>b__1_0(LemonAction x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 174
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[22:54:55.400] [JeviLib] System.IO.FileNotFoundException: Could not load file or assembly 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'UniTask, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'
   at Jevil.JeviLib.OnUpdate()
   at MelonLoader.MelonEvent.<>c.<Invoke>b__1_0(LemonAction x) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 174
   at MelonLoader.MelonEventBase`1.Invoke(Action`1 delegateInvoker) in D:\a\MelonLoader\MelonLoader\MelonLoader\Melons\Events\MelonEvent.cs:line 143
[22:55:05.051] Preferences Saved!

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by galacticatron** [comment]
do you have mcafee

**Comment by KibblesTheKitten** [comment]
You are on patch 3 still.

**Comment by KibblesTheKitten** [comment]
And you also have a mod that wants melon loader 0.5.7, jevilib

**Comment by wildfrogy5** [comment]
im confused do i need to use 0.5.7 or what

**Comment by Ahmedaltaib** [comment]
hey dude, Have you find any solution for this?
because I'm facing the exact same issue. @wildfrogy5
