### ISSUE TITLE
[Bug]: sr2 keeps crashing because of melon loader

### ISSUE THREAD

**Issue by NahName171** [LavaGang/MelonLoader#804]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [X] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [X] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

I'll say right away that I use Google translator, so forgive me for any mistakes in the text. After updating Slime Rancher 2, my game crashes and doesn't even let me see the start screen, and this problem disappears when I delete Melon Loader and then the game starts up smoothly, please help me with this problem.
And I've never used github so I hope I attached the log file correctly

[Latest.log](https://github.com/user-attachments/files/18135673/Latest.log)

### Did you attach your log file?

Yes, I attached my log file to the text box above.

**Comment by NahName171** [comment]
this is what it says in the console before the crash:

[16:04:55.993] [Il2CppAssemblyGenerator] Reading dumped assemblies for interop generation...
[NewEntryPoint] Caught exception invoking PreStart! System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'rid')
   at AsmResolver.PE.DotNet.Metadata.Tables.IndexEncoder.DecodeIndex(UInt32 codedIndex)
   at AsmResolver.DotNet.Serialized.SerializedModuleDefinition.InitializeCustomAttributes()
   at AsmResolver.DotNet.Serialized.SerializedAssemblyDefinition.TryGetTargetFramework(DotNetRuntimeInfo& info)
   at AsmResolver.DotNet.ModuleDefinition.DetectTargetRuntime()
   at AsmResolver.DotNet.Serialized.SerializedModuleDefinition..ctor(PEImage peImage, ModuleReaderParameters readerParameters)
   at AsmResolver.DotNet.ModuleDefinition.FromImage(PEImage peImage, ModuleReaderParameters readerParameters)
   at AsmResolver.DotNet.ModuleDefinition.FromFile(String filePath, ModuleReaderParameters readerParameters)
   at MelonLoader.Il2CppAssemblyGenerator.Packages.Il2CppInterop.<>c__DisplayClass3_0.<ExecuteInterop>b__1(String f) in D:\a\MelonLoader\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Packages\Il2CppInterop.cs:line 63
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Utilities.<>c__DisplayClass2_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MelonLoader.Il2CppAssemblyGenerator.Packages.Il2CppInterop.ExecuteInterop() in D:\a\MelonLoader\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Packages\Il2CppInterop.cs:line 61
   at MelonLoader.Il2CppAssemblyGenerator.Packages.Il2CppInterop.Execute() in D:\a\MelonLoader\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Packages\Il2CppInterop.cs:line 36
   at MelonLoader.Il2CppAssemblyGenerator.Core.Run() in D:\a\MelonLoader\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Core.cs:line 116
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at MelonLoader.Modules.MelonModule.SendMessage(String name, Object[] arguments) in D:\a\MelonLoader\MelonLoader\MelonLoader\Modules\MelonModule.cs:line 118
   at MelonLoader.InternalUtils.Il2CppAssemblyGenerator.Run() in D:\a\MelonLoader\MelonLoader\MelonLoader\InternalUtils\Il2CppAssemblyGenerator.cs:line 29
   at MelonLoader.Core.PreSetup() in D:\a\MelonLoader\MelonLoader\MelonLoader\Core.cs:line 131
   at MelonLoader.InternalUtils.MelonStartScreen.LoadAndRun(LemonFunc`1 functionToWaitForAsync) in D:\a\MelonLoader\MelonLoader\MelonLoader\InternalUtils\MelonStartScreen.cs:line 20
   at MelonLoader.Core.PreStart() in D:\a\MelonLoader\MelonLoader\MelonLoader\Core.cs:line 124
   at MelonLoader.NativeHost.NativeEntryPoint.PreStart() in D:\a\MelonLoader\MelonLoader\MelonLoader.NativeHost\NativeEntryPoint.cs:line 59

**Comment by KibblesTheKitten** [comment]
The latest updates broke ml and all the mods.melon 0.6.4 works but not a single mod does

**Comment by NahName171** [comment]
> The latest updates broke ml and all the mods.melon 0.6.4 works but not a single mod does

What? Latest updates slime rancher 2? Is there any way to fix this?

**Comment by NahName171** [comment]
> The latest updates broke ml and all the mods.melon 0.6.4 works but not a single mod does

Thank you so much for helping, the game works now
