### ISSUE TITLE
Waiting for you to press enter - feel free to copy the error...

### ISSUE THREAD

**Issue by Gabopogi01** [LavaGang/MelonLoader#819]
### All of the following criteria must be met

- [X] All <a href="https://github.com/LavaGang/MelonLoader/blob/master/README.md#requirements">Requirements</a> must be installed.
- [X] Changed the title so that it doesn't just says "[Bug]: "
- [X] I have searched the GitHub issues for my bug, even in the closed issues.

### All of the following are optional to answer

- [ ] Tried reinstalling the Game.
- [X] Tried reinstalling MelonLoader.
- [ ] Tried restarting PC.
- [ ] Was able to see the Start Screen.

### Describe the issue.

what the hell is Waiting for you to press enter - feel free to copy the error...
i pressed the enter but nothing works

### Did you attach your log file?

No, I could not find a log file at `{Game_Directory}\MelonLoader\Latest.log`

**Comment by SamboyCoding** [comment]
If you've got that message, you've got a log. We'll need it to do anything more with this.

**Comment by Gabopogi01** [comment]
here
[21:55:42.367] ------------------------------
[21:55:42.431] MelonLoader v0.6.1 Open-Beta
[21:55:42.434] OS: Windows 10
[21:55:42.435] Hash Code: 696B58144EEC73C72FA36A811CA73312EEE4EC28AD5E3527BDA1E14F388A
[21:55:42.436] ------------------------------
[21:55:42.440] Game Type: Il2cpp
[21:55:42.444] Game Arch: x64
[21:55:42.447] ------------------------------
[21:55:42.451] Core::BasePath = reacted
[21:55:42.452] Game::BasePath = reacted
[21:55:42.453] Game::DataPath = reacted
[21:55:42.454] Game::ApplicationPath = reacted
[21:55:42.455] Runtime Type: net6
[21:55:43.371] ------------------------------
[21:55:43.372] Game Name: BloonsTD6
[21:55:43.373] Game Developer: Ninja Kiwi
[21:55:43.375] Unity Version: 2022.3.49f1
[21:55:43.376] Game Version: UNKNOWN
[21:55:43.376] ------------------------------

[21:55:44.540] Preferences Loaded!

[21:55:44.625] Loading Plugins from 'reacted'...
[21:55:44.630] 0 Plugins loaded.
[21:55:45.404] Loading Il2CppAssemblyGenerator...
[21:55:45.452] [Il2CppAssemblyGenerator] Contacting RemoteAPI...
[21:55:46.218] [Il2CppAssemblyGenerator] RemoteAPI.DumperVersion = null
[21:55:46.219] [Il2CppAssemblyGenerator] RemoteAPI.ObfuscationRegex = null
[21:55:46.220] [Il2CppAssemblyGenerator] RemoteAPI.MappingURL = null
[21:55:46.220] [Il2CppAssemblyGenerator] RemoteAPI.MappingFileSHA512 = null
[21:55:46.253] [Il2CppAssemblyGenerator] Using Dumper Version: 2022.1.0-pre-release.10
[21:55:46.253] [Il2CppAssemblyGenerator] Using Il2CppInterop Version = 1.4.5
[21:55:46.253] [Il2CppAssemblyGenerator] Using Unity Dependencies Version = 2022.3.49
[21:55:46.254] [Il2CppAssemblyGenerator] Using Deobfuscation Regex = null
[21:55:46.255] [Il2CppAssemblyGenerator] Downloading Cpp2IL...
[21:55:46.255] [Il2CppAssemblyGenerator] Downloading https://github.com/SamboyCoding/Cpp2IL/releases/download/2022.1.0-pre-release.10/Cpp2IL-2022.1.0-pre-release.10-Windows-Netframework472.zip to reacted\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL_2022.1.0-pre-release.10.zip
[21:55:54.662] [Il2CppAssemblyGenerator] Processing Cpp2IL...
[21:55:54.665] [Il2CppAssemblyGenerator] Creating Directory reacted\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL
[21:55:54.666] [Il2CppAssemblyGenerator] Extracting reacted\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL_2022.1.0-pre-release.10.zip to reacted\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL
[21:55:54.738] [Il2CppAssemblyGenerator] Downloading UnityDependencies...
[21:55:54.739] [Il2CppAssemblyGenerator] Downloading https://github.com/LavaGang/Unity-Runtime-Libraries/raw/master/2022.3.49.zip to reacted\MelonLoader\Dependencies\Il2CppAssemblyGenerator\UnityDependencies_2022.3.49.zip
[21:56:08.642] [Il2CppAssemblyGenerator] Processing UnityDependencies...
[21:56:08.643] [Il2CppAssemblyGenerator] Creating Directory reacted\MelonLoader\Dependencies\Il2CppAssemblyGenerator\UnityDependencies
[21:56:08.645] [Il2CppAssemblyGenerator] Extracting reacted\MelonLoader\Dependencies\Il2CppAssemblyGenerator\UnityDependencies_2022.3.49.zip to reacted\MelonLoader\Dependencies\Il2CppAssemblyGenerator\UnityDependencies
[21:56:08.753] [Il2CppAssemblyGenerator] Checking GameAssembly...
[21:56:08.975] [Il2CppAssemblyGenerator] Assembly Generation Needed!
[21:56:08.989] [Il2CppAssemblyGenerator] Executing Cpp2IL...
[21:56:08.991] [Il2CppAssemblyGenerator] "reacted\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL\Cpp2IL.exe" --game-path "reacted" --exe-name "BloonsTD6" --use-processor attributeinjector --output-as dummydll
[21:56:09.026] TODO: SetProcessId(12088)
[21:56:09.103] [Il2CppAssemblyGenerator] ===Cpp2IL by Samboy063===
[21:56:09.103] [Il2CppAssemblyGenerator] A Tool to Reverse Unity's "il2cpp" Build Process.
[21:56:09.105] [Il2CppAssemblyGenerator] Version 2022.1.0-pre-release.10
[21:56:09.105] [Il2CppAssemblyGenerator] 
[21:56:09.112] [Il2CppAssemblyGenerator] [Warn] [Program] NO_COLOR set, disabling ANSI color codes as you requested.
[21:56:09.112] [Il2CppAssemblyGenerator] [Info] [Program] Running on Win32NT
[21:56:09.246] [Il2CppAssemblyGenerator] [Info] [Plugins] Loading plugins from reacted\MelonLoader\Dependencies\Il2CppAssemblyGenerator\Cpp2IL\Plugins...
[21:56:09.304] [Il2CppAssemblyGenerator] [Info] [Plugins] Using Plugin: Cpp2IL Built-In
[21:56:09.314] [Il2CppAssemblyGenerator] [Info] [Program] Determined game's unity version to be 2022.3.49a0
[21:56:09.439] [Il2CppAssemblyGenerator] [Info] [Library] Initializing Metadata...
[21:56:09.461] [Il2CppAssemblyGenerator] [Fail] [Program] 
[21:56:09.461] [Il2CppAssemblyGenerator] 
[21:56:09.462] [Il2CppAssemblyGenerator] Cpp2IL.Core.Exceptions.LibCpp2ILInitializationException: Fatal Exception initializing LibCpp2IL! ---> System.FormatException: Unsupported metadata version found! We support 23-29, got 31
[21:56:09.462] [Il2CppAssemblyGenerator]    at LibCpp2IL.Metadata.Il2CppMetadata.ReadFrom(Byte[] bytes, UnityVersion unityVersion) in C:\Users\Sarah\RiderProjects\Cpp2IL\LibCpp2IL\Metadata\Il2CppMetadata.cs:line 71
[21:56:09.463] [Il2CppAssemblyGenerator]    at LibCpp2IL.LibCpp2IlMain.Initialize(Byte[] binaryBytes, Byte[] metadataBytes, UnityVersion unityVersion) in C:\Users\Sarah\RiderProjects\Cpp2IL\LibCpp2IL\LibCpp2IlMain.cs:line 150
[21:56:09.463] [Il2CppAssemblyGenerator]    at LibCpp2IL.LibCpp2IlMain.LoadFromFile(String pePath, String metadataPath, UnityVersion unityVersion) in C:\Users\Sarah\RiderProjects\Cpp2IL\LibCpp2IL\LibCpp2IlMain.cs:line 202
[21:56:09.464] [Il2CppAssemblyGenerator]    at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, UnityVersion unityVersion, Boolean allowUserToInputAddresses) in C:\Users\Sarah\RiderProjects\Cpp2IL\Cpp2IL.Core\Cpp2IlApi.cs:line 54
[21:56:09.465] [Il2CppAssemblyGenerator]    --- End of inner exception stack trace ---
[21:56:09.465] [Il2CppAssemblyGenerator]    at Cpp2IL.Core.Cpp2IlApi.InitializeLibCpp2Il(String assemblyPath, String metadataPath, UnityVersion unityVersion, Boolean allowUserToInputAddresses) in C:\Users\Sarah\RiderProjects\Cpp2IL\Cpp2IL.Core\Cpp2IlApi.cs:line 66
[21:56:09.466] [Il2CppAssemblyGenerator]    at Cpp2IL.Program.MainWithArgs(Cpp2IlRuntimeArgs runtimeArgs) in C:\Users\Sarah\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 487
[21:56:09.466] [Il2CppAssemblyGenerator]    at Cpp2IL.Program.Main(String[] args) in C:\Users\Sarah\RiderProjects\Cpp2IL\Cpp2IL\Program.cs:line 429
[21:56:09.467] [Il2CppAssemblyGenerator] 
[21:56:09.467] [Il2CppAssemblyGenerator] Waiting for you to press enter - feel free to copy the error...

**Comment by SamboyCoding** [comment]
Update to MelonLoader 0.6.6, that has the fix, and that is the version the BTD6 modding communities are using.

**Comment by Gabopogi01** [comment]
ok
